// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod lojban {
    pub mod nesy {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod ast_types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type SelbriId = u32;
            pub type SumtiId = u32;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum PlaceTag {
                Fa,
                Fe,
                Fi,
                Fo,
                Fu,
            }
            impl ::core::fmt::Debug for PlaceTag {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PlaceTag::Fa => f.debug_tuple("PlaceTag::Fa").finish(),
                        PlaceTag::Fe => f.debug_tuple("PlaceTag::Fe").finish(),
                        PlaceTag::Fi => f.debug_tuple("PlaceTag::Fi").finish(),
                        PlaceTag::Fo => f.debug_tuple("PlaceTag::Fo").finish(),
                        PlaceTag::Fu => f.debug_tuple("PlaceTag::Fu").finish(),
                    }
                }
            }
            impl PlaceTag {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> PlaceTag {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => PlaceTag::Fa,
                        1 => PlaceTag::Fe,
                        2 => PlaceTag::Fi,
                        3 => PlaceTag::Fo,
                        4 => PlaceTag::Fu,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Conversion {
                Se,
                Te,
                Ve,
                Xe,
            }
            impl ::core::fmt::Debug for Conversion {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Conversion::Se => f.debug_tuple("Conversion::Se").finish(),
                        Conversion::Te => f.debug_tuple("Conversion::Te").finish(),
                        Conversion::Ve => f.debug_tuple("Conversion::Ve").finish(),
                        Conversion::Xe => f.debug_tuple("Conversion::Xe").finish(),
                    }
                }
            }
            impl Conversion {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Conversion {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Conversion::Se,
                        1 => Conversion::Te,
                        2 => Conversion::Ve,
                        3 => Conversion::Xe,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Connective {
                Je,
                Ja,
                Jo,
                Ju,
            }
            impl ::core::fmt::Debug for Connective {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Connective::Je => f.debug_tuple("Connective::Je").finish(),
                        Connective::Ja => f.debug_tuple("Connective::Ja").finish(),
                        Connective::Jo => f.debug_tuple("Connective::Jo").finish(),
                        Connective::Ju => f.debug_tuple("Connective::Ju").finish(),
                    }
                }
            }
            impl Connective {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Connective {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Connective::Je,
                        1 => Connective::Ja,
                        2 => Connective::Jo,
                        3 => Connective::Ju,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Gadri {
                Lo,
                Le,
                La,
                RoLo,
                RoLe,
            }
            impl ::core::fmt::Debug for Gadri {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Gadri::Lo => f.debug_tuple("Gadri::Lo").finish(),
                        Gadri::Le => f.debug_tuple("Gadri::Le").finish(),
                        Gadri::La => f.debug_tuple("Gadri::La").finish(),
                        Gadri::RoLo => f.debug_tuple("Gadri::RoLo").finish(),
                        Gadri::RoLe => f.debug_tuple("Gadri::RoLe").finish(),
                    }
                }
            }
            impl Gadri {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Gadri {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Gadri::Lo,
                        1 => Gadri::Le,
                        2 => Gadri::La,
                        3 => Gadri::RoLo,
                        4 => Gadri::RoLe,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum RelClauseKind {
                Poi,
                Noi,
            }
            impl ::core::fmt::Debug for RelClauseKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        RelClauseKind::Poi => {
                            f.debug_tuple("RelClauseKind::Poi").finish()
                        }
                        RelClauseKind::Noi => {
                            f.debug_tuple("RelClauseKind::Noi").finish()
                        }
                    }
                }
            }
            impl RelClauseKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> RelClauseKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => RelClauseKind::Poi,
                        1 => RelClauseKind::Noi,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct RelClause {
                pub kind: RelClauseKind,
                pub body_sentence: u32,
            }
            impl ::core::fmt::Debug for RelClause {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RelClause")
                        .field("kind", &self.kind)
                        .field("body-sentence", &self.body_sentence)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum Sumti {
                ProSumti(_rt::String),
                Description((Gadri, SelbriId)),
                Name(_rt::String),
                QuotedLiteral(_rt::String),
                Unspecified,
                Tagged((PlaceTag, SumtiId)),
                Restricted((SumtiId, RelClause)),
            }
            impl ::core::fmt::Debug for Sumti {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Sumti::ProSumti(e) => {
                            f.debug_tuple("Sumti::ProSumti").field(e).finish()
                        }
                        Sumti::Description(e) => {
                            f.debug_tuple("Sumti::Description").field(e).finish()
                        }
                        Sumti::Name(e) => f.debug_tuple("Sumti::Name").field(e).finish(),
                        Sumti::QuotedLiteral(e) => {
                            f.debug_tuple("Sumti::QuotedLiteral").field(e).finish()
                        }
                        Sumti::Unspecified => {
                            f.debug_tuple("Sumti::Unspecified").finish()
                        }
                        Sumti::Tagged(e) => {
                            f.debug_tuple("Sumti::Tagged").field(e).finish()
                        }
                        Sumti::Restricted(e) => {
                            f.debug_tuple("Sumti::Restricted").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub enum Selbri {
                Root(_rt::String),
                Compound(_rt::Vec<_rt::String>),
                Tanru((SelbriId, SelbriId)),
                Converted((Conversion, SelbriId)),
                Negated(SelbriId),
                Grouped(SelbriId),
                WithArgs((SelbriId, _rt::Vec<SumtiId>)),
                Connected((SelbriId, Connective, SelbriId)),
                /// nu abstraction: inner bridi lives in sentences[u32].
                /// Arity is 1 (x1 = event/proposition entity).
                Abstraction(u32),
            }
            impl ::core::fmt::Debug for Selbri {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Selbri::Root(e) => {
                            f.debug_tuple("Selbri::Root").field(e).finish()
                        }
                        Selbri::Compound(e) => {
                            f.debug_tuple("Selbri::Compound").field(e).finish()
                        }
                        Selbri::Tanru(e) => {
                            f.debug_tuple("Selbri::Tanru").field(e).finish()
                        }
                        Selbri::Converted(e) => {
                            f.debug_tuple("Selbri::Converted").field(e).finish()
                        }
                        Selbri::Negated(e) => {
                            f.debug_tuple("Selbri::Negated").field(e).finish()
                        }
                        Selbri::Grouped(e) => {
                            f.debug_tuple("Selbri::Grouped").field(e).finish()
                        }
                        Selbri::WithArgs(e) => {
                            f.debug_tuple("Selbri::WithArgs").field(e).finish()
                        }
                        Selbri::Connected(e) => {
                            f.debug_tuple("Selbri::Connected").field(e).finish()
                        }
                        Selbri::Abstraction(e) => {
                            f.debug_tuple("Selbri::Abstraction").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub struct Bridi {
                pub relation: SelbriId,
                pub head_terms: _rt::Vec<SumtiId>,
                pub tail_terms: _rt::Vec<SumtiId>,
                pub negated: bool,
            }
            impl ::core::fmt::Debug for Bridi {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Bridi")
                        .field("relation", &self.relation)
                        .field("head-terms", &self.head_terms)
                        .field("tail-terms", &self.tail_terms)
                        .field("negated", &self.negated)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct AstBuffer {
                pub selbris: _rt::Vec<Selbri>,
                pub sumtis: _rt::Vec<Sumti>,
                pub sentences: _rt::Vec<Bridi>,
                /// Indices into `sentences` for top-level sentences only.
                /// Rel clause bodies live in `sentences` but are NOT roots.
                pub roots: _rt::Vec<u32>,
            }
            impl ::core::fmt::Debug for AstBuffer {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AstBuffer")
                        .field("selbris", &self.selbris)
                        .field("sumtis", &self.sumtis)
                        .field("sentences", &self.sentences)
                        .field("roots", &self.roots)
                        .finish()
                }
            }
            /// --- Logic Types ---
            #[derive(Clone)]
            pub enum LogicalTerm {
                Variable(_rt::String),
                Constant(_rt::String),
                Description(_rt::String),
                Unspecified,
            }
            impl ::core::fmt::Debug for LogicalTerm {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogicalTerm::Variable(e) => {
                            f.debug_tuple("LogicalTerm::Variable").field(e).finish()
                        }
                        LogicalTerm::Constant(e) => {
                            f.debug_tuple("LogicalTerm::Constant").field(e).finish()
                        }
                        LogicalTerm::Description(e) => {
                            f.debug_tuple("LogicalTerm::Description").field(e).finish()
                        }
                        LogicalTerm::Unspecified => {
                            f.debug_tuple("LogicalTerm::Unspecified").finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub enum LogicNode {
                Predicate((_rt::String, _rt::Vec<LogicalTerm>)),
                AndNode((u32, u32)),
                OrNode((u32, u32)),
                NotNode(u32),
                ExistsNode((_rt::String, u32)),
                ForAllNode((_rt::String, u32)),
            }
            impl ::core::fmt::Debug for LogicNode {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogicNode::Predicate(e) => {
                            f.debug_tuple("LogicNode::Predicate").field(e).finish()
                        }
                        LogicNode::AndNode(e) => {
                            f.debug_tuple("LogicNode::AndNode").field(e).finish()
                        }
                        LogicNode::OrNode(e) => {
                            f.debug_tuple("LogicNode::OrNode").field(e).finish()
                        }
                        LogicNode::NotNode(e) => {
                            f.debug_tuple("LogicNode::NotNode").field(e).finish()
                        }
                        LogicNode::ExistsNode(e) => {
                            f.debug_tuple("LogicNode::ExistsNode").field(e).finish()
                        }
                        LogicNode::ForAllNode(e) => {
                            f.debug_tuple("LogicNode::ForAllNode").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub struct LogicBuffer {
                pub nodes: _rt::Vec<LogicNode>,
                pub roots: _rt::Vec<u32>,
            }
            impl ::core::fmt::Debug for LogicBuffer {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LogicBuffer")
                        .field("nodes", &self.nodes)
                        .field("roots", &self.roots)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod lojban {
        pub mod nesy {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod parser {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type AstBuffer = super::super::super::super::lojban::nesy::ast_types::AstBuffer;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_parse_text_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::parse_text(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::lojban::nesy::ast_types::AstBuffer {
                                selbris: selbris3,
                                sumtis: sumtis3,
                                sentences: sentences3,
                                roots: roots3,
                            } = e;
                            let vec13 = selbris3;
                            let len13 = vec13.len();
                            let layout13 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec13.len() * (4 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result13 = if layout13.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout13).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout13);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec13.into_iter().enumerate() {
                                let base = result13
                                    .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    use super::super::super::super::lojban::nesy::ast_types::Selbri as V12;
                                    match e {
                                        V12::Root(e) => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                            let vec4 = (e.into_bytes()).into_boxed_slice();
                                            let ptr4 = vec4.as_ptr().cast::<u8>();
                                            let len4 = vec4.len();
                                            ::core::mem::forget(vec4);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len4;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr4.cast_mut();
                                        }
                                        V12::Compound(e) => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                            let vec6 = e;
                                            let len6 = vec6.len();
                                            let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                                                vec6.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                                ::core::mem::size_of::<*const u8>(),
                                            );
                                            let result6 = if layout6.size() != 0 {
                                                let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                                                if ptr.is_null() {
                                                    _rt::alloc::handle_alloc_error(layout6);
                                                }
                                                ptr
                                            } else {
                                                ::core::ptr::null_mut()
                                            };
                                            for (i, e) in vec6.into_iter().enumerate() {
                                                let base = result6
                                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let vec5 = (e.into_bytes()).into_boxed_slice();
                                                    let ptr5 = vec5.as_ptr().cast::<u8>();
                                                    let len5 = vec5.len();
                                                    ::core::mem::forget(vec5);
                                                    *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len5;
                                                    *base.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                                                }
                                            }
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len6;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = result6;
                                        }
                                        V12::Tanru(e) => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                            let (t7_0, t7_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t7_0);
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t7_1);
                                        }
                                        V12::Converted(e) => {
                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                            let (t8_0, t8_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (t8_0.clone() as i32) as u8;
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t8_1);
                                        }
                                        V12::Negated(e) => {
                                            *base.add(0).cast::<u8>() = (4i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V12::Grouped(e) => {
                                            *base.add(0).cast::<u8>() = (5i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V12::WithArgs(e) => {
                                            *base.add(0).cast::<u8>() = (6i32) as u8;
                                            let (t9_0, t9_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t9_0);
                                            let vec10 = (t9_1).into_boxed_slice();
                                            let ptr10 = vec10.as_ptr().cast::<u8>();
                                            let len10 = vec10.len();
                                            ::core::mem::forget(vec10);
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len10;
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr10.cast_mut();
                                        }
                                        V12::Connected(e) => {
                                            *base.add(0).cast::<u8>() = (7i32) as u8;
                                            let (t11_0, t11_1, t11_2) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t11_0);
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (t11_1.clone() as i32) as u8;
                                            *base
                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t11_2);
                                        }
                                        V12::Abstraction(e) => {
                                            *base.add(0).cast::<u8>() = (8i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                    }
                                }
                            }
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len13;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result13;
                            let vec22 = sumtis3;
                            let len22 = vec22.len();
                            let layout22 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec22.len() * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result22 = if layout22.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout22).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout22);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec22.into_iter().enumerate() {
                                let base = result22
                                    .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    use super::super::super::super::lojban::nesy::ast_types::Sumti as V21;
                                    match e {
                                        V21::ProSumti(e) => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                            let vec14 = (e.into_bytes()).into_boxed_slice();
                                            let ptr14 = vec14.as_ptr().cast::<u8>();
                                            let len14 = vec14.len();
                                            ::core::mem::forget(vec14);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len14;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr14.cast_mut();
                                        }
                                        V21::Description(e) => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                            let (t15_0, t15_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (t15_0.clone() as i32) as u8;
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t15_1);
                                        }
                                        V21::Name(e) => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                            let vec16 = (e.into_bytes()).into_boxed_slice();
                                            let ptr16 = vec16.as_ptr().cast::<u8>();
                                            let len16 = vec16.len();
                                            ::core::mem::forget(vec16);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len16;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr16.cast_mut();
                                        }
                                        V21::QuotedLiteral(e) => {
                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                            let vec17 = (e.into_bytes()).into_boxed_slice();
                                            let ptr17 = vec17.as_ptr().cast::<u8>();
                                            let len17 = vec17.len();
                                            ::core::mem::forget(vec17);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len17;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr17.cast_mut();
                                        }
                                        V21::Unspecified => {
                                            *base.add(0).cast::<u8>() = (4i32) as u8;
                                        }
                                        V21::Tagged(e) => {
                                            *base.add(0).cast::<u8>() = (5i32) as u8;
                                            let (t18_0, t18_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (t18_0.clone() as i32) as u8;
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t18_1);
                                        }
                                        V21::Restricted(e) => {
                                            *base.add(0).cast::<u8>() = (6i32) as u8;
                                            let (t19_0, t19_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t19_0);
                                            let super::super::super::super::lojban::nesy::ast_types::RelClause {
                                                kind: kind20,
                                                body_sentence: body_sentence20,
                                            } = t19_1;
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>() = (kind20.clone() as i32) as u8;
                                            *base
                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(body_sentence20);
                                        }
                                    }
                                }
                            }
                            *ptr2
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len22;
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result22;
                            let vec26 = sentences3;
                            let len26 = vec26.len();
                            let layout26 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec26.len() * (6 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result26 = if layout26.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout26).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout26);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec26.into_iter().enumerate() {
                                let base = result26
                                    .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::super::lojban::nesy::ast_types::Bridi {
                                        relation: relation23,
                                        head_terms: head_terms23,
                                        tail_terms: tail_terms23,
                                        negated: negated23,
                                    } = e;
                                    *base.add(0).cast::<i32>() = _rt::as_i32(relation23);
                                    let vec24 = (head_terms23).into_boxed_slice();
                                    let ptr24 = vec24.as_ptr().cast::<u8>();
                                    let len24 = vec24.len();
                                    ::core::mem::forget(vec24);
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len24;
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr24.cast_mut();
                                    let vec25 = (tail_terms23).into_boxed_slice();
                                    let ptr25 = vec25.as_ptr().cast::<u8>();
                                    let len25 = vec25.len();
                                    ::core::mem::forget(vec25);
                                    *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len25;
                                    *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr25.cast_mut();
                                    *base
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (match negated23 {
                                        true => 1,
                                        false => 0,
                                    }) as u8;
                                }
                            }
                            *ptr2
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len26;
                            *ptr2
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result26;
                            let vec27 = (roots3).into_boxed_slice();
                            let ptr27 = vec27.as_ptr().cast::<u8>();
                            let len27 = vec27.len();
                            ::core::mem::forget(vec27);
                            *ptr2
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len27;
                            *ptr2
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr27.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec28 = (e.into_bytes()).into_boxed_slice();
                            let ptr28 = vec28.as_ptr().cast::<u8>();
                            let len28 = vec28.len();
                            ::core::mem::forget(vec28);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len28;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr28.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_parse_text<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base14 = l1;
                            let len14 = l2;
                            for i in 0..len14 {
                                let base = base14
                                    .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = i32::from(*base.add(0).cast::<u8>());
                                    match l3 {
                                        0 => {
                                            let l4 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l5 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l4, l5, 1);
                                        }
                                        1 => {
                                            let l6 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l7 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let base10 = l6;
                                            let len10 = l7;
                                            for i in 0..len10 {
                                                let base = base10
                                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let l8 = *base.add(0).cast::<*mut u8>();
                                                    let l9 = *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l8, l9, 1);
                                                }
                                            }
                                            _rt::cabi_dealloc(
                                                base10,
                                                len10 * (2 * ::core::mem::size_of::<*const u8>()),
                                                ::core::mem::size_of::<*const u8>(),
                                            );
                                        }
                                        2 => {}
                                        3 => {}
                                        4 => {}
                                        5 => {}
                                        6 => {
                                            let l11 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l12 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let base13 = l11;
                                            let len13 = l12;
                                            _rt::cabi_dealloc(base13, len13 * 4, 4);
                                        }
                                        7 => {}
                                        _ => {}
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base14,
                                len14 * (4 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l15 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l16 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base24 = l15;
                            let len24 = l16;
                            for i in 0..len24 {
                                let base = base24
                                    .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l17 = i32::from(*base.add(0).cast::<u8>());
                                    match l17 {
                                        0 => {
                                            let l18 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l19 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l18, l19, 1);
                                        }
                                        1 => {}
                                        2 => {
                                            let l20 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l21 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l20, l21, 1);
                                        }
                                        3 => {
                                            let l22 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l23 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l22, l23, 1);
                                        }
                                        4 => {}
                                        5 => {}
                                        _ => {}
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base24,
                                len24 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l25 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l26 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base33 = l25;
                            let len33 = l26;
                            for i in 0..len33 {
                                let base = base33
                                    .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l27 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l28 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base29 = l27;
                                    let len29 = l28;
                                    _rt::cabi_dealloc(base29, len29 * 4, 4);
                                    let l30 = *base
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l31 = *base
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base32 = l30;
                                    let len32 = l31;
                                    _rt::cabi_dealloc(base32, len32 * 4, 4);
                                }
                            }
                            _rt::cabi_dealloc(
                                base33,
                                len33 * (6 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l34 = *arg0
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l35 = *arg0
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base36 = l34;
                            let len36 = l35;
                            _rt::cabi_dealloc(base36, len36 * 4, 4);
                        }
                        _ => {
                            let l37 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l38 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l37, l38, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn parse_text(input: _rt::String) -> Result<AstBuffer, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_lojban_nesy_parser_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "lojban:nesy/parser@0.1.0#parse-text")] unsafe extern "C" fn
                        export_parse_text(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_parse_text_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "cabi_post_lojban:nesy/parser@0.1.0#parse-text")] unsafe extern
                        "C" fn _post_return_parse_text(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_parse_text::<$ty > (arg0) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_lojban_nesy_parser_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 9 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 9
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::alloc;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_parser_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::lojban::nesy::parser::__export_lojban_nesy_parser_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::lojban::nesy::parser);
    };
}
#[doc(inline)]
pub(crate) use __export_parser_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:lojban:nesy@0.1.0:parser-component:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1170] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8b\x08\x01A\x02\x01\
A\x05\x01B0\x01y\x04\0\x09selbri-id\x03\0\0\x01y\x04\0\x08sumti-id\x03\0\x02\x01\
m\x05\x02fa\x02fe\x02fi\x02fo\x02fu\x04\0\x09place-tag\x03\0\x04\x01m\x04\x02se\x02\
te\x02ve\x02xe\x04\0\x0aconversion\x03\0\x06\x01m\x04\x02je\x02ja\x02jo\x02ju\x04\
\0\x0aconnective\x03\0\x08\x01m\x05\x02lo\x02le\x02la\x05ro-lo\x05ro-le\x04\0\x05\
gadri\x03\0\x0a\x01m\x02\x03poi\x03noi\x04\0\x0frel-clause-kind\x03\0\x0c\x01r\x02\
\x04kind\x0d\x0dbody-sentencey\x04\0\x0arel-clause\x03\0\x0e\x01o\x02\x0b\x01\x01\
o\x02\x05\x03\x01o\x02\x03\x0f\x01q\x07\x09pro-sumti\x01s\0\x0bdescription\x01\x10\
\0\x04name\x01s\0\x0equoted-literal\x01s\0\x0bunspecified\0\0\x06tagged\x01\x11\0\
\x0arestricted\x01\x12\0\x04\0\x05sumti\x03\0\x13\x01ps\x01o\x02\x01\x01\x01o\x02\
\x07\x01\x01p\x03\x01o\x02\x01\x18\x01o\x03\x01\x09\x01\x01q\x09\x04root\x01s\0\x08\
compound\x01\x15\0\x05tanru\x01\x16\0\x09converted\x01\x17\0\x07negated\x01\x01\0\
\x07grouped\x01\x01\0\x09with-args\x01\x19\0\x09connected\x01\x1a\0\x0babstracti\
on\x01y\0\x04\0\x06selbri\x03\0\x1b\x01r\x04\x08relation\x01\x0ahead-terms\x18\x0a\
tail-terms\x18\x07negated\x7f\x04\0\x05bridi\x03\0\x1d\x01p\x1c\x01p\x14\x01p\x1e\
\x01py\x01r\x04\x07selbris\x1f\x06sumtis\x20\x09sentences!\x05roots\"\x04\0\x0aa\
st-buffer\x03\0#\x01q\x04\x08variable\x01s\0\x08constant\x01s\0\x0bdescription\x01\
s\0\x0bunspecified\0\0\x04\0\x0clogical-term\x03\0%\x01p&\x01o\x02s'\x01o\x02yy\x01\
o\x02sy\x01q\x06\x09predicate\x01(\0\x08and-node\x01)\0\x07or-node\x01)\0\x08not\
-node\x01y\0\x0bexists-node\x01*\0\x0cfor-all-node\x01*\0\x04\0\x0alogic-node\x03\
\0+\x01p,\x01r\x02\x05nodes-\x05roots\"\x04\0\x0clogic-buffer\x03\0.\x03\0\x1blo\
jban:nesy/ast-types@0.1.0\x05\0\x02\x03\0\0\x0aast-buffer\x01B\x05\x02\x03\x02\x01\
\x01\x04\0\x0aast-buffer\x03\0\0\x01j\x01\x01\x01s\x01@\x01\x05inputs\0\x02\x04\0\
\x0aparse-text\x01\x03\x04\0\x18lojban:nesy/parser@0.1.0\x05\x02\x04\0\"lojban:n\
esy/parser-component@0.1.0\x04\0\x0b\x16\x01\0\x10parser-component\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rus\
t\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
