// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod lojban {
    pub mod nesy {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod logic_types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub enum LogicalTerm {
                Variable(_rt::String),
                Constant(_rt::String),
                Description(_rt::String),
                Unspecified,
                Number(f64),
            }
            impl ::core::fmt::Debug for LogicalTerm {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogicalTerm::Variable(e) => {
                            f.debug_tuple("LogicalTerm::Variable").field(e).finish()
                        }
                        LogicalTerm::Constant(e) => {
                            f.debug_tuple("LogicalTerm::Constant").field(e).finish()
                        }
                        LogicalTerm::Description(e) => {
                            f.debug_tuple("LogicalTerm::Description").field(e).finish()
                        }
                        LogicalTerm::Unspecified => {
                            f.debug_tuple("LogicalTerm::Unspecified").finish()
                        }
                        LogicalTerm::Number(e) => {
                            f.debug_tuple("LogicalTerm::Number").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub enum LogicNode {
                Predicate((_rt::String, _rt::Vec<LogicalTerm>)),
                /// A predicate dispatched to an external compute backend for evaluation.
                ComputeNode((_rt::String, _rt::Vec<LogicalTerm>)),
                AndNode((u32, u32)),
                OrNode((u32, u32)),
                NotNode(u32),
                ExistsNode((_rt::String, u32)),
                ForAllNode((_rt::String, u32)),
                PastNode(u32),
                PresentNode(u32),
                FutureNode(u32),
                /// Exactly N entities satisfy the body: Count(variable-name, count, body-node-id)
                CountNode((_rt::String, u32, u32)),
            }
            impl ::core::fmt::Debug for LogicNode {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogicNode::Predicate(e) => {
                            f.debug_tuple("LogicNode::Predicate").field(e).finish()
                        }
                        LogicNode::ComputeNode(e) => {
                            f.debug_tuple("LogicNode::ComputeNode").field(e).finish()
                        }
                        LogicNode::AndNode(e) => {
                            f.debug_tuple("LogicNode::AndNode").field(e).finish()
                        }
                        LogicNode::OrNode(e) => {
                            f.debug_tuple("LogicNode::OrNode").field(e).finish()
                        }
                        LogicNode::NotNode(e) => {
                            f.debug_tuple("LogicNode::NotNode").field(e).finish()
                        }
                        LogicNode::ExistsNode(e) => {
                            f.debug_tuple("LogicNode::ExistsNode").field(e).finish()
                        }
                        LogicNode::ForAllNode(e) => {
                            f.debug_tuple("LogicNode::ForAllNode").field(e).finish()
                        }
                        LogicNode::PastNode(e) => {
                            f.debug_tuple("LogicNode::PastNode").field(e).finish()
                        }
                        LogicNode::PresentNode(e) => {
                            f.debug_tuple("LogicNode::PresentNode").field(e).finish()
                        }
                        LogicNode::FutureNode(e) => {
                            f.debug_tuple("LogicNode::FutureNode").field(e).finish()
                        }
                        LogicNode::CountNode(e) => {
                            f.debug_tuple("LogicNode::CountNode").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub struct LogicBuffer {
                pub nodes: _rt::Vec<LogicNode>,
                pub roots: _rt::Vec<u32>,
            }
            impl ::core::fmt::Debug for LogicBuffer {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LogicBuffer")
                        .field("nodes", &self.nodes)
                        .field("roots", &self.roots)
                        .finish()
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod compute_backend {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type LogicalTerm = super::super::super::lojban::nesy::logic_types::LogicalTerm;
            #[allow(unused_unsafe, clippy::all)]
            /// Evaluate whether a computed predicate holds for fully-ground arguments.
            pub fn evaluate(
                relation: &str,
                args: &[LogicalTerm],
            ) -> Result<bool, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = relation;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec5 = args;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            use super::super::super::lojban::nesy::logic_types::LogicalTerm as V4;
                            match e {
                                V4::Variable(e) => {
                                    *base.add(0).cast::<u8>() = (0i32) as u8;
                                    let vec1 = e;
                                    let ptr1 = vec1.as_ptr().cast::<u8>();
                                    let len1 = vec1.len();
                                    *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len1;
                                    *base.add(8).cast::<*mut u8>() = ptr1.cast_mut();
                                }
                                V4::Constant(e) => {
                                    *base.add(0).cast::<u8>() = (1i32) as u8;
                                    let vec2 = e;
                                    let ptr2 = vec2.as_ptr().cast::<u8>();
                                    let len2 = vec2.len();
                                    *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len2;
                                    *base.add(8).cast::<*mut u8>() = ptr2.cast_mut();
                                }
                                V4::Description(e) => {
                                    *base.add(0).cast::<u8>() = (2i32) as u8;
                                    let vec3 = e;
                                    let ptr3 = vec3.as_ptr().cast::<u8>();
                                    let len3 = vec3.len();
                                    *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len3;
                                    *base.add(8).cast::<*mut u8>() = ptr3.cast_mut();
                                }
                                V4::Unspecified => {
                                    *base.add(0).cast::<u8>() = (3i32) as u8;
                                }
                                V4::Number(e) => {
                                    *base.add(0).cast::<u8>() = (4i32) as u8;
                                    *base.add(8).cast::<f64>() = _rt::as_f64(e);
                                }
                            }
                        }
                    }
                    let ptr6 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "lojban:nesy/compute-backend@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "evaluate"]
                        fn wit_import7(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import7(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe { wit_import7(ptr0.cast_mut(), len0, result5, len5, ptr6) };
                    let l8 = i32::from(*ptr6.add(0).cast::<u8>());
                    let result13 = match l8 {
                        0 => {
                            let e = {
                                let l9 = i32::from(
                                    *ptr6.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                _rt::bool_lift(l9 as u8)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l10 = *ptr6
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l11 = *ptr6
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len12 = l11;
                                let bytes12 = _rt::Vec::from_raw_parts(
                                    l10.cast(),
                                    len12,
                                    len12,
                                );
                                _rt::string_lift(bytes12)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    if layout5.size() != 0 {
                        _rt::alloc::dealloc(result5.cast(), layout5);
                    }
                    result13
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod lojban {
        pub mod nesy {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod reasoning {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type LogicBuffer = super::super::super::super::lojban::nesy::logic_types::LogicBuffer;
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct KnowledgeBase {
                    handle: _rt::Resource<KnowledgeBase>,
                }
                type _KnowledgeBaseRep<T> = Option<T>;
                impl KnowledgeBase {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `KnowledgeBase`.
                    pub fn new<T: GuestKnowledgeBase>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _KnowledgeBaseRep<T> = Some(val);
                        let ptr: *mut _KnowledgeBaseRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestKnowledgeBase>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestKnowledgeBase>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestKnowledgeBase>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _KnowledgeBaseRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestKnowledgeBase>(
                        &self,
                    ) -> *mut _KnowledgeBaseRep<T> {
                        KnowledgeBase::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`KnowledgeBase`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct KnowledgeBaseBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a KnowledgeBase>,
                }
                impl<'a> KnowledgeBaseBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestKnowledgeBase>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _KnowledgeBaseRep<T> {
                        KnowledgeBase::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for KnowledgeBase {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]lojban:nesy/reasoning@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]knowledge-base"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_knowledge_base_cabi<
                    T: GuestKnowledgeBase,
                >() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = KnowledgeBase::new(T::new());
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_knowledge_base_assert_fact_cabi<
                    T: GuestKnowledgeBase,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base59 = arg1;
                    let len59 = arg2;
                    let mut result59 = _rt::Vec::with_capacity(len59);
                    for i in 0..len59 {
                        let base = base59
                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                        let e59 = {
                            let l0 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::lojban::nesy::logic_types::LogicNode as V58;
                            let v58 = match l0 {
                                0 => {
                                    let e58 = {
                                        let l1 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l2 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len3 = l2;
                                        let bytes3 = _rt::Vec::from_raw_parts(
                                            l1.cast(),
                                            len3,
                                            len3,
                                        );
                                        let l4 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let base18 = l4;
                                        let len18 = l5;
                                        let mut result18 = _rt::Vec::with_capacity(len18);
                                        for i in 0..len18 {
                                            let base = base18
                                                .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                            let e18 = {
                                                let l6 = i32::from(*base.add(0).cast::<u8>());
                                                use super::super::super::super::lojban::nesy::logic_types::LogicalTerm as V17;
                                                let v17 = match l6 {
                                                    0 => {
                                                        let e17 = {
                                                            let l7 = *base.add(8).cast::<*mut u8>();
                                                            let l8 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len9 = l8;
                                                            let bytes9 = _rt::Vec::from_raw_parts(
                                                                l7.cast(),
                                                                len9,
                                                                len9,
                                                            );
                                                            _rt::string_lift(bytes9)
                                                        };
                                                        V17::Variable(e17)
                                                    }
                                                    1 => {
                                                        let e17 = {
                                                            let l10 = *base.add(8).cast::<*mut u8>();
                                                            let l11 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len12 = l11;
                                                            let bytes12 = _rt::Vec::from_raw_parts(
                                                                l10.cast(),
                                                                len12,
                                                                len12,
                                                            );
                                                            _rt::string_lift(bytes12)
                                                        };
                                                        V17::Constant(e17)
                                                    }
                                                    2 => {
                                                        let e17 = {
                                                            let l13 = *base.add(8).cast::<*mut u8>();
                                                            let l14 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len15 = l14;
                                                            let bytes15 = _rt::Vec::from_raw_parts(
                                                                l13.cast(),
                                                                len15,
                                                                len15,
                                                            );
                                                            _rt::string_lift(bytes15)
                                                        };
                                                        V17::Description(e17)
                                                    }
                                                    3 => V17::Unspecified,
                                                    n => {
                                                        debug_assert_eq!(n, 4, "invalid enum discriminant");
                                                        let e17 = {
                                                            let l16 = *base.add(8).cast::<f64>();
                                                            l16
                                                        };
                                                        V17::Number(e17)
                                                    }
                                                };
                                                v17
                                            };
                                            result18.push(e18);
                                        }
                                        _rt::cabi_dealloc(
                                            base18,
                                            len18 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                            8,
                                        );
                                        (_rt::string_lift(bytes3), result18)
                                    };
                                    V58::Predicate(e58)
                                }
                                1 => {
                                    let e58 = {
                                        let l19 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l20 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len21 = l20;
                                        let bytes21 = _rt::Vec::from_raw_parts(
                                            l19.cast(),
                                            len21,
                                            len21,
                                        );
                                        let l22 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l23 = *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let base36 = l22;
                                        let len36 = l23;
                                        let mut result36 = _rt::Vec::with_capacity(len36);
                                        for i in 0..len36 {
                                            let base = base36
                                                .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                            let e36 = {
                                                let l24 = i32::from(*base.add(0).cast::<u8>());
                                                use super::super::super::super::lojban::nesy::logic_types::LogicalTerm as V35;
                                                let v35 = match l24 {
                                                    0 => {
                                                        let e35 = {
                                                            let l25 = *base.add(8).cast::<*mut u8>();
                                                            let l26 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len27 = l26;
                                                            let bytes27 = _rt::Vec::from_raw_parts(
                                                                l25.cast(),
                                                                len27,
                                                                len27,
                                                            );
                                                            _rt::string_lift(bytes27)
                                                        };
                                                        V35::Variable(e35)
                                                    }
                                                    1 => {
                                                        let e35 = {
                                                            let l28 = *base.add(8).cast::<*mut u8>();
                                                            let l29 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len30 = l29;
                                                            let bytes30 = _rt::Vec::from_raw_parts(
                                                                l28.cast(),
                                                                len30,
                                                                len30,
                                                            );
                                                            _rt::string_lift(bytes30)
                                                        };
                                                        V35::Constant(e35)
                                                    }
                                                    2 => {
                                                        let e35 = {
                                                            let l31 = *base.add(8).cast::<*mut u8>();
                                                            let l32 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len33 = l32;
                                                            let bytes33 = _rt::Vec::from_raw_parts(
                                                                l31.cast(),
                                                                len33,
                                                                len33,
                                                            );
                                                            _rt::string_lift(bytes33)
                                                        };
                                                        V35::Description(e35)
                                                    }
                                                    3 => V35::Unspecified,
                                                    n => {
                                                        debug_assert_eq!(n, 4, "invalid enum discriminant");
                                                        let e35 = {
                                                            let l34 = *base.add(8).cast::<f64>();
                                                            l34
                                                        };
                                                        V35::Number(e35)
                                                    }
                                                };
                                                v35
                                            };
                                            result36.push(e36);
                                        }
                                        _rt::cabi_dealloc(
                                            base36,
                                            len36 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                            8,
                                        );
                                        (_rt::string_lift(bytes21), result36)
                                    };
                                    V58::ComputeNode(e58)
                                }
                                2 => {
                                    let e58 = {
                                        let l37 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l38 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (l37 as u32, l38 as u32)
                                    };
                                    V58::AndNode(e58)
                                }
                                3 => {
                                    let e58 = {
                                        let l39 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l40 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (l39 as u32, l40 as u32)
                                    };
                                    V58::OrNode(e58)
                                }
                                4 => {
                                    let e58 = {
                                        let l41 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l41 as u32
                                    };
                                    V58::NotNode(e58)
                                }
                                5 => {
                                    let e58 = {
                                        let l42 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l43 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len44 = l43;
                                        let bytes44 = _rt::Vec::from_raw_parts(
                                            l42.cast(),
                                            len44,
                                            len44,
                                        );
                                        let l45 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (_rt::string_lift(bytes44), l45 as u32)
                                    };
                                    V58::ExistsNode(e58)
                                }
                                6 => {
                                    let e58 = {
                                        let l46 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l47 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len48 = l47;
                                        let bytes48 = _rt::Vec::from_raw_parts(
                                            l46.cast(),
                                            len48,
                                            len48,
                                        );
                                        let l49 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (_rt::string_lift(bytes48), l49 as u32)
                                    };
                                    V58::ForAllNode(e58)
                                }
                                7 => {
                                    let e58 = {
                                        let l50 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l50 as u32
                                    };
                                    V58::PastNode(e58)
                                }
                                8 => {
                                    let e58 = {
                                        let l51 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l51 as u32
                                    };
                                    V58::PresentNode(e58)
                                }
                                9 => {
                                    let e58 = {
                                        let l52 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l52 as u32
                                    };
                                    V58::FutureNode(e58)
                                }
                                n => {
                                    debug_assert_eq!(n, 10, "invalid enum discriminant");
                                    let e58 = {
                                        let l53 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l54 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len55 = l54;
                                        let bytes55 = _rt::Vec::from_raw_parts(
                                            l53.cast(),
                                            len55,
                                            len55,
                                        );
                                        let l56 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l57 = *base
                                            .add(4 + 3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (_rt::string_lift(bytes55), l56 as u32, l57 as u32)
                                    };
                                    V58::CountNode(e58)
                                }
                            };
                            v58
                        };
                        result59.push(e59);
                    }
                    _rt::cabi_dealloc(
                        base59,
                        len59 * (5 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let len60 = arg4;
                    let result61 = T::assert_fact(
                        unsafe { KnowledgeBaseBorrow::lift(arg0 as u32 as usize) }.get(),
                        super::super::super::super::lojban::nesy::logic_types::LogicBuffer {
                            nodes: result59,
                            roots: _rt::Vec::from_raw_parts(arg3.cast(), len60, len60),
                        },
                    );
                    let ptr62 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result61 {
                        Ok(_) => {
                            *ptr62.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr62.add(0).cast::<u8>() = (1i32) as u8;
                            let vec63 = (e.into_bytes()).into_boxed_slice();
                            let ptr63 = vec63.as_ptr().cast::<u8>();
                            let len63 = vec63.len();
                            ::core::mem::forget(vec63);
                            *ptr62
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len63;
                            *ptr62
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr63.cast_mut();
                        }
                    };
                    ptr62
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_knowledge_base_assert_fact<
                    T: GuestKnowledgeBase,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_knowledge_base_query_entailment_cabi<
                    T: GuestKnowledgeBase,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base59 = arg1;
                    let len59 = arg2;
                    let mut result59 = _rt::Vec::with_capacity(len59);
                    for i in 0..len59 {
                        let base = base59
                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                        let e59 = {
                            let l0 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::lojban::nesy::logic_types::LogicNode as V58;
                            let v58 = match l0 {
                                0 => {
                                    let e58 = {
                                        let l1 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l2 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len3 = l2;
                                        let bytes3 = _rt::Vec::from_raw_parts(
                                            l1.cast(),
                                            len3,
                                            len3,
                                        );
                                        let l4 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let base18 = l4;
                                        let len18 = l5;
                                        let mut result18 = _rt::Vec::with_capacity(len18);
                                        for i in 0..len18 {
                                            let base = base18
                                                .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                            let e18 = {
                                                let l6 = i32::from(*base.add(0).cast::<u8>());
                                                use super::super::super::super::lojban::nesy::logic_types::LogicalTerm as V17;
                                                let v17 = match l6 {
                                                    0 => {
                                                        let e17 = {
                                                            let l7 = *base.add(8).cast::<*mut u8>();
                                                            let l8 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len9 = l8;
                                                            let bytes9 = _rt::Vec::from_raw_parts(
                                                                l7.cast(),
                                                                len9,
                                                                len9,
                                                            );
                                                            _rt::string_lift(bytes9)
                                                        };
                                                        V17::Variable(e17)
                                                    }
                                                    1 => {
                                                        let e17 = {
                                                            let l10 = *base.add(8).cast::<*mut u8>();
                                                            let l11 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len12 = l11;
                                                            let bytes12 = _rt::Vec::from_raw_parts(
                                                                l10.cast(),
                                                                len12,
                                                                len12,
                                                            );
                                                            _rt::string_lift(bytes12)
                                                        };
                                                        V17::Constant(e17)
                                                    }
                                                    2 => {
                                                        let e17 = {
                                                            let l13 = *base.add(8).cast::<*mut u8>();
                                                            let l14 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len15 = l14;
                                                            let bytes15 = _rt::Vec::from_raw_parts(
                                                                l13.cast(),
                                                                len15,
                                                                len15,
                                                            );
                                                            _rt::string_lift(bytes15)
                                                        };
                                                        V17::Description(e17)
                                                    }
                                                    3 => V17::Unspecified,
                                                    n => {
                                                        debug_assert_eq!(n, 4, "invalid enum discriminant");
                                                        let e17 = {
                                                            let l16 = *base.add(8).cast::<f64>();
                                                            l16
                                                        };
                                                        V17::Number(e17)
                                                    }
                                                };
                                                v17
                                            };
                                            result18.push(e18);
                                        }
                                        _rt::cabi_dealloc(
                                            base18,
                                            len18 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                            8,
                                        );
                                        (_rt::string_lift(bytes3), result18)
                                    };
                                    V58::Predicate(e58)
                                }
                                1 => {
                                    let e58 = {
                                        let l19 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l20 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len21 = l20;
                                        let bytes21 = _rt::Vec::from_raw_parts(
                                            l19.cast(),
                                            len21,
                                            len21,
                                        );
                                        let l22 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l23 = *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let base36 = l22;
                                        let len36 = l23;
                                        let mut result36 = _rt::Vec::with_capacity(len36);
                                        for i in 0..len36 {
                                            let base = base36
                                                .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                            let e36 = {
                                                let l24 = i32::from(*base.add(0).cast::<u8>());
                                                use super::super::super::super::lojban::nesy::logic_types::LogicalTerm as V35;
                                                let v35 = match l24 {
                                                    0 => {
                                                        let e35 = {
                                                            let l25 = *base.add(8).cast::<*mut u8>();
                                                            let l26 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len27 = l26;
                                                            let bytes27 = _rt::Vec::from_raw_parts(
                                                                l25.cast(),
                                                                len27,
                                                                len27,
                                                            );
                                                            _rt::string_lift(bytes27)
                                                        };
                                                        V35::Variable(e35)
                                                    }
                                                    1 => {
                                                        let e35 = {
                                                            let l28 = *base.add(8).cast::<*mut u8>();
                                                            let l29 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len30 = l29;
                                                            let bytes30 = _rt::Vec::from_raw_parts(
                                                                l28.cast(),
                                                                len30,
                                                                len30,
                                                            );
                                                            _rt::string_lift(bytes30)
                                                        };
                                                        V35::Constant(e35)
                                                    }
                                                    2 => {
                                                        let e35 = {
                                                            let l31 = *base.add(8).cast::<*mut u8>();
                                                            let l32 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            let len33 = l32;
                                                            let bytes33 = _rt::Vec::from_raw_parts(
                                                                l31.cast(),
                                                                len33,
                                                                len33,
                                                            );
                                                            _rt::string_lift(bytes33)
                                                        };
                                                        V35::Description(e35)
                                                    }
                                                    3 => V35::Unspecified,
                                                    n => {
                                                        debug_assert_eq!(n, 4, "invalid enum discriminant");
                                                        let e35 = {
                                                            let l34 = *base.add(8).cast::<f64>();
                                                            l34
                                                        };
                                                        V35::Number(e35)
                                                    }
                                                };
                                                v35
                                            };
                                            result36.push(e36);
                                        }
                                        _rt::cabi_dealloc(
                                            base36,
                                            len36 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                            8,
                                        );
                                        (_rt::string_lift(bytes21), result36)
                                    };
                                    V58::ComputeNode(e58)
                                }
                                2 => {
                                    let e58 = {
                                        let l37 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l38 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (l37 as u32, l38 as u32)
                                    };
                                    V58::AndNode(e58)
                                }
                                3 => {
                                    let e58 = {
                                        let l39 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l40 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (l39 as u32, l40 as u32)
                                    };
                                    V58::OrNode(e58)
                                }
                                4 => {
                                    let e58 = {
                                        let l41 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l41 as u32
                                    };
                                    V58::NotNode(e58)
                                }
                                5 => {
                                    let e58 = {
                                        let l42 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l43 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len44 = l43;
                                        let bytes44 = _rt::Vec::from_raw_parts(
                                            l42.cast(),
                                            len44,
                                            len44,
                                        );
                                        let l45 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (_rt::string_lift(bytes44), l45 as u32)
                                    };
                                    V58::ExistsNode(e58)
                                }
                                6 => {
                                    let e58 = {
                                        let l46 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l47 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len48 = l47;
                                        let bytes48 = _rt::Vec::from_raw_parts(
                                            l46.cast(),
                                            len48,
                                            len48,
                                        );
                                        let l49 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (_rt::string_lift(bytes48), l49 as u32)
                                    };
                                    V58::ForAllNode(e58)
                                }
                                7 => {
                                    let e58 = {
                                        let l50 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l50 as u32
                                    };
                                    V58::PastNode(e58)
                                }
                                8 => {
                                    let e58 = {
                                        let l51 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l51 as u32
                                    };
                                    V58::PresentNode(e58)
                                }
                                9 => {
                                    let e58 = {
                                        let l52 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l52 as u32
                                    };
                                    V58::FutureNode(e58)
                                }
                                n => {
                                    debug_assert_eq!(n, 10, "invalid enum discriminant");
                                    let e58 = {
                                        let l53 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l54 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len55 = l54;
                                        let bytes55 = _rt::Vec::from_raw_parts(
                                            l53.cast(),
                                            len55,
                                            len55,
                                        );
                                        let l56 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l57 = *base
                                            .add(4 + 3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (_rt::string_lift(bytes55), l56 as u32, l57 as u32)
                                    };
                                    V58::CountNode(e58)
                                }
                            };
                            v58
                        };
                        result59.push(e59);
                    }
                    _rt::cabi_dealloc(
                        base59,
                        len59 * (5 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let len60 = arg4;
                    let result61 = T::query_entailment(
                        unsafe { KnowledgeBaseBorrow::lift(arg0 as u32 as usize) }.get(),
                        super::super::super::super::lojban::nesy::logic_types::LogicBuffer {
                            nodes: result59,
                            roots: _rt::Vec::from_raw_parts(arg3.cast(), len60, len60),
                        },
                    );
                    let ptr62 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result61 {
                        Ok(e) => {
                            *ptr62.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr62
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match e {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(e) => {
                            *ptr62.add(0).cast::<u8>() = (1i32) as u8;
                            let vec63 = (e.into_bytes()).into_boxed_slice();
                            let ptr63 = vec63.as_ptr().cast::<u8>();
                            let len63 = vec63.len();
                            ::core::mem::forget(vec63);
                            *ptr62
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len63;
                            *ptr62
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr63.cast_mut();
                        }
                    };
                    ptr62
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_knowledge_base_query_entailment<
                    T: GuestKnowledgeBase,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_knowledge_base_reset_cabi<
                    T: GuestKnowledgeBase,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::reset(
                        unsafe { KnowledgeBaseBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_knowledge_base_reset<
                    T: GuestKnowledgeBase,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                pub trait Guest {
                    type KnowledgeBase: GuestKnowledgeBase;
                }
                pub trait GuestKnowledgeBase: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]lojban:nesy/reasoning@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]knowledge-base"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]lojban:nesy/reasoning@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]knowledge-base"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    /// Create a fresh KB with FOL schema loaded.
                    fn new() -> Self;
                    /// Assert FOL facts into this KB.
                    fn assert_fact(&self, logic: LogicBuffer) -> Result<(), _rt::String>;
                    /// Query whether FOL formula is entailed by this KB.
                    fn query_entailment(
                        &self,
                        logic: LogicBuffer,
                    ) -> Result<bool, _rt::String>;
                    /// Reset this KB to fresh state (clear all facts, Skolems, rules).
                    fn reset(&self) -> Result<(), _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_lojban_nesy_reasoning_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "lojban:nesy/reasoning@0.1.0#[constructor]knowledge-base")]
                        unsafe extern "C" fn export_constructor_knowledge_base() -> i32 {
                        unsafe { $($path_to_types)*::
                        _export_constructor_knowledge_base_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::KnowledgeBase > () } } #[unsafe
                        (export_name =
                        "lojban:nesy/reasoning@0.1.0#[method]knowledge-base.assert-fact")]
                        unsafe extern "C" fn
                        export_method_knowledge_base_assert_fact(arg0 : * mut u8, arg1 :
                        * mut u8, arg2 : usize, arg3 : * mut u8, arg4 : usize,) -> * mut
                        u8 { unsafe { $($path_to_types)*::
                        _export_method_knowledge_base_assert_fact_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::KnowledgeBase > (arg0, arg1, arg2,
                        arg3, arg4) } } #[unsafe (export_name =
                        "cabi_post_lojban:nesy/reasoning@0.1.0#[method]knowledge-base.assert-fact")]
                        unsafe extern "C" fn
                        _post_return_method_knowledge_base_assert_fact(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*::
                        __post_return_method_knowledge_base_assert_fact::<<$ty as
                        $($path_to_types)*:: Guest >::KnowledgeBase > (arg0) } } #[unsafe
                        (export_name =
                        "lojban:nesy/reasoning@0.1.0#[method]knowledge-base.query-entailment")]
                        unsafe extern "C" fn
                        export_method_knowledge_base_query_entailment(arg0 : * mut u8,
                        arg1 : * mut u8, arg2 : usize, arg3 : * mut u8, arg4 : usize,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_knowledge_base_query_entailment_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::KnowledgeBase > (arg0, arg1, arg2,
                        arg3, arg4) } } #[unsafe (export_name =
                        "cabi_post_lojban:nesy/reasoning@0.1.0#[method]knowledge-base.query-entailment")]
                        unsafe extern "C" fn
                        _post_return_method_knowledge_base_query_entailment(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_knowledge_base_query_entailment::<<$ty as
                        $($path_to_types)*:: Guest >::KnowledgeBase > (arg0) } } #[unsafe
                        (export_name =
                        "lojban:nesy/reasoning@0.1.0#[method]knowledge-base.reset")]
                        unsafe extern "C" fn export_method_knowledge_base_reset(arg0 : *
                        mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_knowledge_base_reset_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::KnowledgeBase > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_lojban:nesy/reasoning@0.1.0#[method]knowledge-base.reset")]
                        unsafe extern "C" fn
                        _post_return_method_knowledge_base_reset(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_knowledge_base_reset::<<$ty as
                        $($path_to_types)*:: Guest >::KnowledgeBase > (arg0) } } const _
                        : () = { #[doc(hidden)] #[unsafe (export_name =
                        "lojban:nesy/reasoning@0.1.0#[dtor]knowledge-base")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: KnowledgeBase::dtor::< <$ty
                        as $($path_to_types)*:: Guest >::KnowledgeBase > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_lojban_nesy_reasoning_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_reasoning_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::lojban::nesy::reasoning::__export_lojban_nesy_reasoning_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::lojban::nesy::reasoning);
    };
}
#[doc(inline)]
pub(crate) use __export_reasoning_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:lojban:nesy@0.1.0:reasoning-component:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 979] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc9\x06\x01A\x02\x01\
A\x08\x01B\x0d\x01q\x05\x08variable\x01s\0\x08constant\x01s\0\x0bdescription\x01\
s\0\x0bunspecified\0\0\x06number\x01u\0\x04\0\x0clogical-term\x03\0\0\x01p\x01\x01\
o\x02s\x02\x01o\x02yy\x01o\x02sy\x01o\x03syy\x01q\x0b\x09predicate\x01\x03\0\x0c\
compute-node\x01\x03\0\x08and-node\x01\x04\0\x07or-node\x01\x04\0\x08not-node\x01\
y\0\x0bexists-node\x01\x05\0\x0cfor-all-node\x01\x05\0\x09past-node\x01y\0\x0cpr\
esent-node\x01y\0\x0bfuture-node\x01y\0\x0acount-node\x01\x06\0\x04\0\x0alogic-n\
ode\x03\0\x07\x01p\x08\x01py\x01r\x02\x05nodes\x09\x05roots\x0a\x04\0\x0clogic-b\
uffer\x03\0\x0b\x03\0\x1dlojban:nesy/logic-types@0.1.0\x05\0\x02\x03\0\0\x0clogi\
cal-term\x01B\x06\x02\x03\x02\x01\x01\x04\0\x0clogical-term\x03\0\0\x01p\x01\x01\
j\x01\x7f\x01s\x01@\x02\x08relations\x04args\x02\0\x03\x04\0\x08evaluate\x01\x04\
\x03\0!lojban:nesy/compute-backend@0.1.0\x05\x02\x02\x03\0\0\x0clogic-buffer\x01\
B\x0f\x02\x03\x02\x01\x03\x04\0\x0clogic-buffer\x03\0\0\x04\0\x0eknowledge-base\x03\
\x01\x01i\x02\x01@\0\0\x03\x04\0\x1b[constructor]knowledge-base\x01\x04\x01h\x02\
\x01j\0\x01s\x01@\x02\x04self\x05\x05logic\x01\0\x06\x04\0\"[method]knowledge-ba\
se.assert-fact\x01\x07\x01j\x01\x7f\x01s\x01@\x02\x04self\x05\x05logic\x01\0\x08\
\x04\0'[method]knowledge-base.query-entailment\x01\x09\x01@\x01\x04self\x05\0\x06\
\x04\0\x1c[method]knowledge-base.reset\x01\x0a\x04\0\x1blojban:nesy/reasoning@0.\
1.0\x05\x04\x04\0%lojban:nesy/reasoning-component@0.1.0\x04\0\x0b\x19\x01\0\x13r\
easoning-component\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compon\
ent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
