// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod lojban {
    pub mod nesy {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod ast_types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type SelbriId = u32;
            pub type SumtiId = u32;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum PlaceTag {
                Fa,
                Fe,
                Fi,
                Fo,
                Fu,
            }
            impl ::core::fmt::Debug for PlaceTag {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PlaceTag::Fa => f.debug_tuple("PlaceTag::Fa").finish(),
                        PlaceTag::Fe => f.debug_tuple("PlaceTag::Fe").finish(),
                        PlaceTag::Fi => f.debug_tuple("PlaceTag::Fi").finish(),
                        PlaceTag::Fo => f.debug_tuple("PlaceTag::Fo").finish(),
                        PlaceTag::Fu => f.debug_tuple("PlaceTag::Fu").finish(),
                    }
                }
            }
            impl PlaceTag {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> PlaceTag {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => PlaceTag::Fa,
                        1 => PlaceTag::Fe,
                        2 => PlaceTag::Fi,
                        3 => PlaceTag::Fo,
                        4 => PlaceTag::Fu,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Conversion {
                Se,
                Te,
                Ve,
                Xe,
            }
            impl ::core::fmt::Debug for Conversion {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Conversion::Se => f.debug_tuple("Conversion::Se").finish(),
                        Conversion::Te => f.debug_tuple("Conversion::Te").finish(),
                        Conversion::Ve => f.debug_tuple("Conversion::Ve").finish(),
                        Conversion::Xe => f.debug_tuple("Conversion::Xe").finish(),
                    }
                }
            }
            impl Conversion {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Conversion {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Conversion::Se,
                        1 => Conversion::Te,
                        2 => Conversion::Ve,
                        3 => Conversion::Xe,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Connective {
                Je,
                Ja,
                Jo,
                Ju,
            }
            impl ::core::fmt::Debug for Connective {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Connective::Je => f.debug_tuple("Connective::Je").finish(),
                        Connective::Ja => f.debug_tuple("Connective::Ja").finish(),
                        Connective::Jo => f.debug_tuple("Connective::Jo").finish(),
                        Connective::Ju => f.debug_tuple("Connective::Ju").finish(),
                    }
                }
            }
            impl Connective {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Connective {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Connective::Je,
                        1 => Connective::Ja,
                        2 => Connective::Jo,
                        3 => Connective::Ju,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Gadri {
                Lo,
                Le,
                La,
                RoLo,
                RoLe,
            }
            impl ::core::fmt::Debug for Gadri {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Gadri::Lo => f.debug_tuple("Gadri::Lo").finish(),
                        Gadri::Le => f.debug_tuple("Gadri::Le").finish(),
                        Gadri::La => f.debug_tuple("Gadri::La").finish(),
                        Gadri::RoLo => f.debug_tuple("Gadri::RoLo").finish(),
                        Gadri::RoLe => f.debug_tuple("Gadri::RoLe").finish(),
                    }
                }
            }
            impl Gadri {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Gadri {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Gadri::Lo,
                        1 => Gadri::Le,
                        2 => Gadri::La,
                        3 => Gadri::RoLo,
                        4 => Gadri::RoLe,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum RelClauseKind {
                Poi,
                Noi,
            }
            impl ::core::fmt::Debug for RelClauseKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        RelClauseKind::Poi => {
                            f.debug_tuple("RelClauseKind::Poi").finish()
                        }
                        RelClauseKind::Noi => {
                            f.debug_tuple("RelClauseKind::Noi").finish()
                        }
                    }
                }
            }
            impl RelClauseKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> RelClauseKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => RelClauseKind::Poi,
                        1 => RelClauseKind::Noi,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct RelClause {
                pub kind: RelClauseKind,
                pub body_sentence: u32,
            }
            impl ::core::fmt::Debug for RelClause {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RelClause")
                        .field("kind", &self.kind)
                        .field("body-sentence", &self.body_sentence)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum Sumti {
                ProSumti(_rt::String),
                Description((Gadri, SelbriId)),
                Name(_rt::String),
                QuotedLiteral(_rt::String),
                Unspecified,
                Tagged((PlaceTag, SumtiId)),
                Restricted((SumtiId, RelClause)),
                Number(f64),
                /// Sumti connective: left .e/.a/.o/.u [nai] right
                /// Fields: (left-sumti-id, connective, right-negated, right-sumti-id)
                Connected((SumtiId, Connective, bool, SumtiId)),
            }
            impl ::core::fmt::Debug for Sumti {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Sumti::ProSumti(e) => {
                            f.debug_tuple("Sumti::ProSumti").field(e).finish()
                        }
                        Sumti::Description(e) => {
                            f.debug_tuple("Sumti::Description").field(e).finish()
                        }
                        Sumti::Name(e) => f.debug_tuple("Sumti::Name").field(e).finish(),
                        Sumti::QuotedLiteral(e) => {
                            f.debug_tuple("Sumti::QuotedLiteral").field(e).finish()
                        }
                        Sumti::Unspecified => {
                            f.debug_tuple("Sumti::Unspecified").finish()
                        }
                        Sumti::Tagged(e) => {
                            f.debug_tuple("Sumti::Tagged").field(e).finish()
                        }
                        Sumti::Restricted(e) => {
                            f.debug_tuple("Sumti::Restricted").field(e).finish()
                        }
                        Sumti::Number(e) => {
                            f.debug_tuple("Sumti::Number").field(e).finish()
                        }
                        Sumti::Connected(e) => {
                            f.debug_tuple("Sumti::Connected").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub enum Selbri {
                Root(_rt::String),
                Compound(_rt::Vec<_rt::String>),
                Tanru((SelbriId, SelbriId)),
                Converted((Conversion, SelbriId)),
                Negated(SelbriId),
                Grouped(SelbriId),
                WithArgs((SelbriId, _rt::Vec<SumtiId>)),
                Connected((SelbriId, Connective, SelbriId)),
                /// nu abstraction: inner bridi lives in sentences[u32].
                /// Arity is 1 (x1 = event/proposition entity).
                Abstraction(u32),
            }
            impl ::core::fmt::Debug for Selbri {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Selbri::Root(e) => {
                            f.debug_tuple("Selbri::Root").field(e).finish()
                        }
                        Selbri::Compound(e) => {
                            f.debug_tuple("Selbri::Compound").field(e).finish()
                        }
                        Selbri::Tanru(e) => {
                            f.debug_tuple("Selbri::Tanru").field(e).finish()
                        }
                        Selbri::Converted(e) => {
                            f.debug_tuple("Selbri::Converted").field(e).finish()
                        }
                        Selbri::Negated(e) => {
                            f.debug_tuple("Selbri::Negated").field(e).finish()
                        }
                        Selbri::Grouped(e) => {
                            f.debug_tuple("Selbri::Grouped").field(e).finish()
                        }
                        Selbri::WithArgs(e) => {
                            f.debug_tuple("Selbri::WithArgs").field(e).finish()
                        }
                        Selbri::Connected(e) => {
                            f.debug_tuple("Selbri::Connected").field(e).finish()
                        }
                        Selbri::Abstraction(e) => {
                            f.debug_tuple("Selbri::Abstraction").field(e).finish()
                        }
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Tense {
                Pu,
                Ca,
                Ba,
            }
            impl ::core::fmt::Debug for Tense {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Tense::Pu => f.debug_tuple("Tense::Pu").finish(),
                        Tense::Ca => f.debug_tuple("Tense::Ca").finish(),
                        Tense::Ba => f.debug_tuple("Tense::Ba").finish(),
                    }
                }
            }
            impl Tense {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Tense {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Tense::Pu,
                        1 => Tense::Ca,
                        2 => Tense::Ba,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct Bridi {
                pub relation: SelbriId,
                pub head_terms: _rt::Vec<SumtiId>,
                pub tail_terms: _rt::Vec<SumtiId>,
                pub negated: bool,
                pub tense: Option<Tense>,
            }
            impl ::core::fmt::Debug for Bridi {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Bridi")
                        .field("relation", &self.relation)
                        .field("head-terms", &self.head_terms)
                        .field("tail-terms", &self.tail_terms)
                        .field("negated", &self.negated)
                        .field("tense", &self.tense)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum SentenceConnective {
                GanaiGi,
                GeGi,
                GaGi,
            }
            impl ::core::fmt::Debug for SentenceConnective {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        SentenceConnective::GanaiGi => {
                            f.debug_tuple("SentenceConnective::GanaiGi").finish()
                        }
                        SentenceConnective::GeGi => {
                            f.debug_tuple("SentenceConnective::GeGi").finish()
                        }
                        SentenceConnective::GaGi => {
                            f.debug_tuple("SentenceConnective::GaGi").finish()
                        }
                    }
                }
            }
            impl SentenceConnective {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> SentenceConnective {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => SentenceConnective::GanaiGi,
                        1 => SentenceConnective::GeGi,
                        2 => SentenceConnective::GaGi,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub enum Sentence {
                Simple(Bridi),
                Connected((SentenceConnective, u32, u32)),
            }
            impl ::core::fmt::Debug for Sentence {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Sentence::Simple(e) => {
                            f.debug_tuple("Sentence::Simple").field(e).finish()
                        }
                        Sentence::Connected(e) => {
                            f.debug_tuple("Sentence::Connected").field(e).finish()
                        }
                    }
                }
            }
            /// Update ast-buffer to hold the new `sentence` variant:
            #[derive(Clone)]
            pub struct AstBuffer {
                pub selbris: _rt::Vec<Selbri>,
                pub sumtis: _rt::Vec<Sumti>,
                pub sentences: _rt::Vec<Sentence>,
                /// <-- CHANGED from bridi to sentence
                pub roots: _rt::Vec<u32>,
            }
            impl ::core::fmt::Debug for AstBuffer {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AstBuffer")
                        .field("selbris", &self.selbris)
                        .field("sumtis", &self.sumtis)
                        .field("sentences", &self.sentences)
                        .field("roots", &self.roots)
                        .finish()
                }
            }
            /// --- Logic Types ---
            #[derive(Clone)]
            pub enum LogicalTerm {
                Variable(_rt::String),
                Constant(_rt::String),
                Description(_rt::String),
                Unspecified,
                Number(f64),
            }
            impl ::core::fmt::Debug for LogicalTerm {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogicalTerm::Variable(e) => {
                            f.debug_tuple("LogicalTerm::Variable").field(e).finish()
                        }
                        LogicalTerm::Constant(e) => {
                            f.debug_tuple("LogicalTerm::Constant").field(e).finish()
                        }
                        LogicalTerm::Description(e) => {
                            f.debug_tuple("LogicalTerm::Description").field(e).finish()
                        }
                        LogicalTerm::Unspecified => {
                            f.debug_tuple("LogicalTerm::Unspecified").finish()
                        }
                        LogicalTerm::Number(e) => {
                            f.debug_tuple("LogicalTerm::Number").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub enum LogicNode {
                Predicate((_rt::String, _rt::Vec<LogicalTerm>)),
                AndNode((u32, u32)),
                OrNode((u32, u32)),
                NotNode(u32),
                ExistsNode((_rt::String, u32)),
                ForAllNode((_rt::String, u32)),
                PastNode(u32),
                PresentNode(u32),
                FutureNode(u32),
            }
            impl ::core::fmt::Debug for LogicNode {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogicNode::Predicate(e) => {
                            f.debug_tuple("LogicNode::Predicate").field(e).finish()
                        }
                        LogicNode::AndNode(e) => {
                            f.debug_tuple("LogicNode::AndNode").field(e).finish()
                        }
                        LogicNode::OrNode(e) => {
                            f.debug_tuple("LogicNode::OrNode").field(e).finish()
                        }
                        LogicNode::NotNode(e) => {
                            f.debug_tuple("LogicNode::NotNode").field(e).finish()
                        }
                        LogicNode::ExistsNode(e) => {
                            f.debug_tuple("LogicNode::ExistsNode").field(e).finish()
                        }
                        LogicNode::ForAllNode(e) => {
                            f.debug_tuple("LogicNode::ForAllNode").field(e).finish()
                        }
                        LogicNode::PastNode(e) => {
                            f.debug_tuple("LogicNode::PastNode").field(e).finish()
                        }
                        LogicNode::PresentNode(e) => {
                            f.debug_tuple("LogicNode::PresentNode").field(e).finish()
                        }
                        LogicNode::FutureNode(e) => {
                            f.debug_tuple("LogicNode::FutureNode").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub struct LogicBuffer {
                pub nodes: _rt::Vec<LogicNode>,
                pub roots: _rt::Vec<u32>,
            }
            impl ::core::fmt::Debug for LogicBuffer {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LogicBuffer")
                        .field("nodes", &self.nodes)
                        .field("roots", &self.roots)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod lojban {
        pub mod nesy {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod semantics {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type AstBuffer = super::super::super::super::lojban::nesy::ast_types::AstBuffer;
                pub type LogicBuffer = super::super::super::super::lojban::nesy::ast_types::LogicBuffer;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_compile_buffer_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base25 = arg0;
                    let len25 = arg1;
                    let mut result25 = _rt::Vec::with_capacity(len25);
                    for i in 0..len25 {
                        let base = base25
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e25 = {
                            let l0 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::lojban::nesy::ast_types::Selbri as V24;
                            let v24 = match l0 {
                                0 => {
                                    let e24 = {
                                        let l1 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l2 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len3 = l2;
                                        let bytes3 = _rt::Vec::from_raw_parts(
                                            l1.cast(),
                                            len3,
                                            len3,
                                        );
                                        _rt::string_lift(bytes3)
                                    };
                                    V24::Root(e24)
                                }
                                1 => {
                                    let e24 = {
                                        let l4 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let base9 = l4;
                                        let len9 = l5;
                                        let mut result9 = _rt::Vec::with_capacity(len9);
                                        for i in 0..len9 {
                                            let base = base9
                                                .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                            let e9 = {
                                                let l6 = *base.add(0).cast::<*mut u8>();
                                                let l7 = *base
                                                    .add(::core::mem::size_of::<*const u8>())
                                                    .cast::<usize>();
                                                let len8 = l7;
                                                let bytes8 = _rt::Vec::from_raw_parts(
                                                    l6.cast(),
                                                    len8,
                                                    len8,
                                                );
                                                _rt::string_lift(bytes8)
                                            };
                                            result9.push(e9);
                                        }
                                        _rt::cabi_dealloc(
                                            base9,
                                            len9 * (2 * ::core::mem::size_of::<*const u8>()),
                                            ::core::mem::size_of::<*const u8>(),
                                        );
                                        result9
                                    };
                                    V24::Compound(e24)
                                }
                                2 => {
                                    let e24 = {
                                        let l10 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l11 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (l10 as u32, l11 as u32)
                                    };
                                    V24::Tanru(e24)
                                }
                                3 => {
                                    let e24 = {
                                        let l12 = i32::from(
                                            *base.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                        );
                                        let l13 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::Conversion::_lift(
                                                l12 as u8,
                                            ),
                                            l13 as u32,
                                        )
                                    };
                                    V24::Converted(e24)
                                }
                                4 => {
                                    let e24 = {
                                        let l14 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l14 as u32
                                    };
                                    V24::Negated(e24)
                                }
                                5 => {
                                    let e24 = {
                                        let l15 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l15 as u32
                                    };
                                    V24::Grouped(e24)
                                }
                                6 => {
                                    let e24 = {
                                        let l16 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l17 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l18 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len19 = l18;
                                        (
                                            l16 as u32,
                                            _rt::Vec::from_raw_parts(l17.cast(), len19, len19),
                                        )
                                    };
                                    V24::WithArgs(e24)
                                }
                                7 => {
                                    let e24 = {
                                        let l20 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l21 = i32::from(
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        let l22 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (
                                            l20 as u32,
                                            super::super::super::super::lojban::nesy::ast_types::Connective::_lift(
                                                l21 as u8,
                                            ),
                                            l22 as u32,
                                        )
                                    };
                                    V24::Connected(e24)
                                }
                                n => {
                                    debug_assert_eq!(n, 8, "invalid enum discriminant");
                                    let e24 = {
                                        let l23 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l23 as u32
                                    };
                                    V24::Abstraction(e24)
                                }
                            };
                            v24
                        };
                        result25.push(e25);
                    }
                    _rt::cabi_dealloc(
                        base25,
                        len25 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let base49 = arg2;
                    let len49 = arg3;
                    let mut result49 = _rt::Vec::with_capacity(len49);
                    for i in 0..len49 {
                        let base = base49.add(i * 24);
                        let e49 = {
                            let l26 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::lojban::nesy::ast_types::Sumti as V48;
                            let v48 = match l26 {
                                0 => {
                                    let e48 = {
                                        let l27 = *base.add(8).cast::<*mut u8>();
                                        let l28 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len29 = l28;
                                        let bytes29 = _rt::Vec::from_raw_parts(
                                            l27.cast(),
                                            len29,
                                            len29,
                                        );
                                        _rt::string_lift(bytes29)
                                    };
                                    V48::ProSumti(e48)
                                }
                                1 => {
                                    let e48 = {
                                        let l30 = i32::from(*base.add(8).cast::<u8>());
                                        let l31 = *base.add(12).cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::Gadri::_lift(
                                                l30 as u8,
                                            ),
                                            l31 as u32,
                                        )
                                    };
                                    V48::Description(e48)
                                }
                                2 => {
                                    let e48 = {
                                        let l32 = *base.add(8).cast::<*mut u8>();
                                        let l33 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len34 = l33;
                                        let bytes34 = _rt::Vec::from_raw_parts(
                                            l32.cast(),
                                            len34,
                                            len34,
                                        );
                                        _rt::string_lift(bytes34)
                                    };
                                    V48::Name(e48)
                                }
                                3 => {
                                    let e48 = {
                                        let l35 = *base.add(8).cast::<*mut u8>();
                                        let l36 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len37 = l36;
                                        let bytes37 = _rt::Vec::from_raw_parts(
                                            l35.cast(),
                                            len37,
                                            len37,
                                        );
                                        _rt::string_lift(bytes37)
                                    };
                                    V48::QuotedLiteral(e48)
                                }
                                4 => V48::Unspecified,
                                5 => {
                                    let e48 = {
                                        let l38 = i32::from(*base.add(8).cast::<u8>());
                                        let l39 = *base.add(12).cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::PlaceTag::_lift(
                                                l38 as u8,
                                            ),
                                            l39 as u32,
                                        )
                                    };
                                    V48::Tagged(e48)
                                }
                                6 => {
                                    let e48 = {
                                        let l40 = *base.add(8).cast::<i32>();
                                        let l41 = i32::from(*base.add(12).cast::<u8>());
                                        let l42 = *base.add(16).cast::<i32>();
                                        (
                                            l40 as u32,
                                            super::super::super::super::lojban::nesy::ast_types::RelClause {
                                                kind: super::super::super::super::lojban::nesy::ast_types::RelClauseKind::_lift(
                                                    l41 as u8,
                                                ),
                                                body_sentence: l42 as u32,
                                            },
                                        )
                                    };
                                    V48::Restricted(e48)
                                }
                                7 => {
                                    let e48 = {
                                        let l43 = *base.add(8).cast::<f64>();
                                        l43
                                    };
                                    V48::Number(e48)
                                }
                                n => {
                                    debug_assert_eq!(n, 8, "invalid enum discriminant");
                                    let e48 = {
                                        let l44 = *base.add(8).cast::<i32>();
                                        let l45 = i32::from(*base.add(12).cast::<u8>());
                                        let l46 = i32::from(*base.add(13).cast::<u8>());
                                        let l47 = *base.add(16).cast::<i32>();
                                        (
                                            l44 as u32,
                                            super::super::super::super::lojban::nesy::ast_types::Connective::_lift(
                                                l45 as u8,
                                            ),
                                            _rt::bool_lift(l46 as u8),
                                            l47 as u32,
                                        )
                                    };
                                    V48::Connected(e48)
                                }
                            };
                            v48
                        };
                        result49.push(e49);
                    }
                    _rt::cabi_dealloc(base49, len49 * 24, 8);
                    let base65 = arg4;
                    let len65 = arg5;
                    let mut result65 = _rt::Vec::with_capacity(len65);
                    for i in 0..len65 {
                        let base = base65
                            .add(i * (7 * ::core::mem::size_of::<*const u8>()));
                        let e65 = {
                            let l50 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::lojban::nesy::ast_types::Sentence as V64;
                            let v64 = match l50 {
                                0 => {
                                    let e64 = {
                                        let l51 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l52 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l53 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len54 = l53;
                                        let l55 = *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l56 = *base
                                            .add(5 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len57 = l56;
                                        let l58 = i32::from(
                                            *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        let l59 = i32::from(
                                            *base
                                                .add(1 + 6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        super::super::super::super::lojban::nesy::ast_types::Bridi {
                                            relation: l51 as u32,
                                            head_terms: _rt::Vec::from_raw_parts(
                                                l52.cast(),
                                                len54,
                                                len54,
                                            ),
                                            tail_terms: _rt::Vec::from_raw_parts(
                                                l55.cast(),
                                                len57,
                                                len57,
                                            ),
                                            negated: _rt::bool_lift(l58 as u8),
                                            tense: match l59 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l60 = i32::from(
                                                            *base
                                                                .add(2 + 6 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<u8>(),
                                                        );
                                                        super::super::super::super::lojban::nesy::ast_types::Tense::_lift(
                                                            l60 as u8,
                                                        )
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                        }
                                    };
                                    V64::Simple(e64)
                                }
                                n => {
                                    debug_assert_eq!(n, 1, "invalid enum discriminant");
                                    let e64 = {
                                        let l61 = i32::from(
                                            *base.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                        );
                                        let l62 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l63 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::SentenceConnective::_lift(
                                                l61 as u8,
                                            ),
                                            l62 as u32,
                                            l63 as u32,
                                        )
                                    };
                                    V64::Connected(e64)
                                }
                            };
                            v64
                        };
                        result65.push(e65);
                    }
                    _rt::cabi_dealloc(
                        base65,
                        len65 * (7 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let len66 = arg7;
                    let result67 = T::compile_buffer(super::super::super::super::lojban::nesy::ast_types::AstBuffer {
                        selbris: result25,
                        sumtis: result49,
                        sentences: result65,
                        roots: _rt::Vec::from_raw_parts(arg6.cast(), len66, len66),
                    });
                    let ptr68 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result67 {
                        Ok(e) => {
                            *ptr68.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::lojban::nesy::ast_types::LogicBuffer {
                                nodes: nodes69,
                                roots: roots69,
                            } = e;
                            let vec84 = nodes69;
                            let len84 = vec84.len();
                            let layout84 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec84.len() * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result84 = if layout84.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout84).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout84);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec84.into_iter().enumerate() {
                                let base = result84
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    use super::super::super::super::lojban::nesy::ast_types::LogicNode as V83;
                                    match e {
                                        V83::Predicate(e) => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                            let (t70_0, t70_1) = e;
                                            let vec71 = (t70_0.into_bytes()).into_boxed_slice();
                                            let ptr71 = vec71.as_ptr().cast::<u8>();
                                            let len71 = vec71.len();
                                            ::core::mem::forget(vec71);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len71;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr71.cast_mut();
                                            let vec76 = t70_1;
                                            let len76 = vec76.len();
                                            let layout76 = _rt::alloc::Layout::from_size_align_unchecked(
                                                vec76.len() * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                                8,
                                            );
                                            let result76 = if layout76.size() != 0 {
                                                let ptr = _rt::alloc::alloc(layout76).cast::<u8>();
                                                if ptr.is_null() {
                                                    _rt::alloc::handle_alloc_error(layout76);
                                                }
                                                ptr
                                            } else {
                                                ::core::ptr::null_mut()
                                            };
                                            for (i, e) in vec76.into_iter().enumerate() {
                                                let base = result76
                                                    .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    use super::super::super::super::lojban::nesy::ast_types::LogicalTerm as V75;
                                                    match e {
                                                        V75::Variable(e) => {
                                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                                            let vec72 = (e.into_bytes()).into_boxed_slice();
                                                            let ptr72 = vec72.as_ptr().cast::<u8>();
                                                            let len72 = vec72.len();
                                                            ::core::mem::forget(vec72);
                                                            *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>() = len72;
                                                            *base.add(8).cast::<*mut u8>() = ptr72.cast_mut();
                                                        }
                                                        V75::Constant(e) => {
                                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                                            let vec73 = (e.into_bytes()).into_boxed_slice();
                                                            let ptr73 = vec73.as_ptr().cast::<u8>();
                                                            let len73 = vec73.len();
                                                            ::core::mem::forget(vec73);
                                                            *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>() = len73;
                                                            *base.add(8).cast::<*mut u8>() = ptr73.cast_mut();
                                                        }
                                                        V75::Description(e) => {
                                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                                            let vec74 = (e.into_bytes()).into_boxed_slice();
                                                            let ptr74 = vec74.as_ptr().cast::<u8>();
                                                            let len74 = vec74.len();
                                                            ::core::mem::forget(vec74);
                                                            *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>() = len74;
                                                            *base.add(8).cast::<*mut u8>() = ptr74.cast_mut();
                                                        }
                                                        V75::Unspecified => {
                                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                                        }
                                                        V75::Number(e) => {
                                                            *base.add(0).cast::<u8>() = (4i32) as u8;
                                                            *base.add(8).cast::<f64>() = _rt::as_f64(e);
                                                        }
                                                    }
                                                }
                                            }
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len76;
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = result76;
                                        }
                                        V83::AndNode(e) => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                            let (t77_0, t77_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t77_0);
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t77_1);
                                        }
                                        V83::OrNode(e) => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                            let (t78_0, t78_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t78_0);
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t78_1);
                                        }
                                        V83::NotNode(e) => {
                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V83::ExistsNode(e) => {
                                            *base.add(0).cast::<u8>() = (4i32) as u8;
                                            let (t79_0, t79_1) = e;
                                            let vec80 = (t79_0.into_bytes()).into_boxed_slice();
                                            let ptr80 = vec80.as_ptr().cast::<u8>();
                                            let len80 = vec80.len();
                                            ::core::mem::forget(vec80);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len80;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr80.cast_mut();
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t79_1);
                                        }
                                        V83::ForAllNode(e) => {
                                            *base.add(0).cast::<u8>() = (5i32) as u8;
                                            let (t81_0, t81_1) = e;
                                            let vec82 = (t81_0.into_bytes()).into_boxed_slice();
                                            let ptr82 = vec82.as_ptr().cast::<u8>();
                                            let len82 = vec82.len();
                                            ::core::mem::forget(vec82);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len82;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr82.cast_mut();
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t81_1);
                                        }
                                        V83::PastNode(e) => {
                                            *base.add(0).cast::<u8>() = (6i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V83::PresentNode(e) => {
                                            *base.add(0).cast::<u8>() = (7i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V83::FutureNode(e) => {
                                            *base.add(0).cast::<u8>() = (8i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                    }
                                }
                            }
                            *ptr68
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len84;
                            *ptr68
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result84;
                            let vec85 = (roots69).into_boxed_slice();
                            let ptr85 = vec85.as_ptr().cast::<u8>();
                            let len85 = vec85.len();
                            ::core::mem::forget(vec85);
                            *ptr68
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len85;
                            *ptr68
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr85.cast_mut();
                        }
                        Err(e) => {
                            *ptr68.add(0).cast::<u8>() = (1i32) as u8;
                            let vec86 = (e.into_bytes()).into_boxed_slice();
                            let ptr86 = vec86.as_ptr().cast::<u8>();
                            let len86 = vec86.len();
                            ::core::mem::forget(vec86);
                            *ptr68
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len86;
                            *ptr68
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr86.cast_mut();
                        }
                    };
                    ptr68
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_compile_buffer<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base20 = l1;
                            let len20 = l2;
                            for i in 0..len20 {
                                let base = base20
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = i32::from(*base.add(0).cast::<u8>());
                                    match l3 {
                                        0 => {
                                            let l4 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l5 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l4, l5, 1);
                                            let l6 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l7 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let base15 = l6;
                                            let len15 = l7;
                                            for i in 0..len15 {
                                                let base = base15
                                                    .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let l8 = i32::from(*base.add(0).cast::<u8>());
                                                    match l8 {
                                                        0 => {
                                                            let l9 = *base.add(8).cast::<*mut u8>();
                                                            let l10 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            _rt::cabi_dealloc(l9, l10, 1);
                                                        }
                                                        1 => {
                                                            let l11 = *base.add(8).cast::<*mut u8>();
                                                            let l12 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            _rt::cabi_dealloc(l11, l12, 1);
                                                        }
                                                        2 => {
                                                            let l13 = *base.add(8).cast::<*mut u8>();
                                                            let l14 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            _rt::cabi_dealloc(l13, l14, 1);
                                                        }
                                                        3 => {}
                                                        _ => {}
                                                    }
                                                }
                                            }
                                            _rt::cabi_dealloc(
                                                base15,
                                                len15 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                                8,
                                            );
                                        }
                                        1 => {}
                                        2 => {}
                                        3 => {}
                                        4 => {
                                            let l16 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l17 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l16, l17, 1);
                                        }
                                        5 => {
                                            let l18 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l19 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l18, l19, 1);
                                        }
                                        6 => {}
                                        7 => {}
                                        _ => {}
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base20,
                                len20 * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l21 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l22 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base23 = l21;
                            let len23 = l22;
                            _rt::cabi_dealloc(base23, len23 * 4, 4);
                        }
                        _ => {
                            let l24 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l25 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l24, l25, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn compile_buffer(
                        ast: AstBuffer,
                    ) -> Result<LogicBuffer, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_lojban_nesy_semantics_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "lojban:nesy/semantics@0.1.0#compile-buffer")] unsafe extern "C"
                        fn export_compile_buffer(arg0 : * mut u8, arg1 : usize, arg2 : *
                        mut u8, arg3 : usize, arg4 : * mut u8, arg5 : usize, arg6 : * mut
                        u8, arg7 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_compile_buffer_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7) } } #[unsafe (export_name =
                        "cabi_post_lojban:nesy/semantics@0.1.0#compile-buffer")] unsafe
                        extern "C" fn _post_return_compile_buffer(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_compile_buffer::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_lojban_nesy_semantics_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::alloc;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_semantics_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::lojban::nesy::semantics::__export_lojban_nesy_semantics_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::lojban::nesy::semantics);
    };
}
#[doc(inline)]
pub(crate) use __export_semantics_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:lojban:nesy@0.1.0:semantics-component:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1433] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8f\x0a\x01A\x02\x01\
A\x06\x01B9\x01y\x04\0\x09selbri-id\x03\0\0\x01y\x04\0\x08sumti-id\x03\0\x02\x01\
m\x05\x02fa\x02fe\x02fi\x02fo\x02fu\x04\0\x09place-tag\x03\0\x04\x01m\x04\x02se\x02\
te\x02ve\x02xe\x04\0\x0aconversion\x03\0\x06\x01m\x04\x02je\x02ja\x02jo\x02ju\x04\
\0\x0aconnective\x03\0\x08\x01m\x05\x02lo\x02le\x02la\x05ro-lo\x05ro-le\x04\0\x05\
gadri\x03\0\x0a\x01m\x02\x03poi\x03noi\x04\0\x0frel-clause-kind\x03\0\x0c\x01r\x02\
\x04kind\x0d\x0dbody-sentencey\x04\0\x0arel-clause\x03\0\x0e\x01o\x02\x0b\x01\x01\
o\x02\x05\x03\x01o\x02\x03\x0f\x01o\x04\x03\x09\x7f\x03\x01q\x09\x09pro-sumti\x01\
s\0\x0bdescription\x01\x10\0\x04name\x01s\0\x0equoted-literal\x01s\0\x0bunspecif\
ied\0\0\x06tagged\x01\x11\0\x0arestricted\x01\x12\0\x06number\x01u\0\x09connecte\
d\x01\x13\0\x04\0\x05sumti\x03\0\x14\x01ps\x01o\x02\x01\x01\x01o\x02\x07\x01\x01\
p\x03\x01o\x02\x01\x19\x01o\x03\x01\x09\x01\x01q\x09\x04root\x01s\0\x08compound\x01\
\x16\0\x05tanru\x01\x17\0\x09converted\x01\x18\0\x07negated\x01\x01\0\x07grouped\
\x01\x01\0\x09with-args\x01\x1a\0\x09connected\x01\x1b\0\x0babstraction\x01y\0\x04\
\0\x06selbri\x03\0\x1c\x01m\x03\x02pu\x02ca\x02ba\x04\0\x05tense\x03\0\x1e\x01k\x1f\
\x01r\x05\x08relation\x01\x0ahead-terms\x19\x0atail-terms\x19\x07negated\x7f\x05\
tense\x20\x04\0\x05bridi\x03\0!\x01m\x03\x08ganai-gi\x05ge-gi\x05ga-gi\x04\0\x13\
sentence-connective\x03\0#\x01o\x03$yy\x01q\x02\x06simple\x01\"\0\x09connected\x01\
%\0\x04\0\x08sentence\x03\0&\x01p\x1d\x01p\x15\x01p'\x01py\x01r\x04\x07selbris(\x06\
sumtis)\x09sentences*\x05roots+\x04\0\x0aast-buffer\x03\0,\x01q\x05\x08variable\x01\
s\0\x08constant\x01s\0\x0bdescription\x01s\0\x0bunspecified\0\0\x06number\x01u\0\
\x04\0\x0clogical-term\x03\0.\x01p/\x01o\x02s0\x01o\x02yy\x01o\x02sy\x01q\x09\x09\
predicate\x011\0\x08and-node\x012\0\x07or-node\x012\0\x08not-node\x01y\0\x0bexis\
ts-node\x013\0\x0cfor-all-node\x013\0\x09past-node\x01y\0\x0cpresent-node\x01y\0\
\x0bfuture-node\x01y\0\x04\0\x0alogic-node\x03\04\x01p5\x01r\x02\x05nodes6\x05ro\
ots+\x04\0\x0clogic-buffer\x03\07\x03\0\x1blojban:nesy/ast-types@0.1.0\x05\0\x02\
\x03\0\0\x0aast-buffer\x02\x03\0\0\x0clogic-buffer\x01B\x07\x02\x03\x02\x01\x01\x04\
\0\x0aast-buffer\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0clogic-buffer\x03\0\x02\x01\
j\x01\x03\x01s\x01@\x01\x03ast\x01\0\x04\x04\0\x0ecompile-buffer\x01\x05\x04\0\x1b\
lojban:nesy/semantics@0.1.0\x05\x03\x04\0%lojban:nesy/semantics-component@0.1.0\x04\
\0\x0b\x19\x01\0\x13semantics-component\x03\0\0\0G\x09producers\x01\x0cprocessed\
-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
