// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod lojban {
    pub mod nesy {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod ast_types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type SelbriId = u32;
            pub type SumtiId = u32;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum PlaceTag {
                Fa,
                Fe,
                Fi,
                Fo,
                Fu,
            }
            impl ::core::fmt::Debug for PlaceTag {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PlaceTag::Fa => f.debug_tuple("PlaceTag::Fa").finish(),
                        PlaceTag::Fe => f.debug_tuple("PlaceTag::Fe").finish(),
                        PlaceTag::Fi => f.debug_tuple("PlaceTag::Fi").finish(),
                        PlaceTag::Fo => f.debug_tuple("PlaceTag::Fo").finish(),
                        PlaceTag::Fu => f.debug_tuple("PlaceTag::Fu").finish(),
                    }
                }
            }
            impl PlaceTag {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> PlaceTag {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => PlaceTag::Fa,
                        1 => PlaceTag::Fe,
                        2 => PlaceTag::Fi,
                        3 => PlaceTag::Fo,
                        4 => PlaceTag::Fu,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum BaiTag {
                Ria,
                Nii,
                Mui,
                Kiu,
                Pio,
                Bai,
            }
            impl ::core::fmt::Debug for BaiTag {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        BaiTag::Ria => f.debug_tuple("BaiTag::Ria").finish(),
                        BaiTag::Nii => f.debug_tuple("BaiTag::Nii").finish(),
                        BaiTag::Mui => f.debug_tuple("BaiTag::Mui").finish(),
                        BaiTag::Kiu => f.debug_tuple("BaiTag::Kiu").finish(),
                        BaiTag::Pio => f.debug_tuple("BaiTag::Pio").finish(),
                        BaiTag::Bai => f.debug_tuple("BaiTag::Bai").finish(),
                    }
                }
            }
            impl BaiTag {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> BaiTag {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => BaiTag::Ria,
                        1 => BaiTag::Nii,
                        2 => BaiTag::Mui,
                        3 => BaiTag::Kiu,
                        4 => BaiTag::Pio,
                        5 => BaiTag::Bai,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone, Copy)]
            pub enum ModalTag {
                Fixed(BaiTag),
                Fio(SelbriId),
            }
            impl ::core::fmt::Debug for ModalTag {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ModalTag::Fixed(e) => {
                            f.debug_tuple("ModalTag::Fixed").field(e).finish()
                        }
                        ModalTag::Fio(e) => {
                            f.debug_tuple("ModalTag::Fio").field(e).finish()
                        }
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Conversion {
                Se,
                Te,
                Ve,
                Xe,
            }
            impl ::core::fmt::Debug for Conversion {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Conversion::Se => f.debug_tuple("Conversion::Se").finish(),
                        Conversion::Te => f.debug_tuple("Conversion::Te").finish(),
                        Conversion::Ve => f.debug_tuple("Conversion::Ve").finish(),
                        Conversion::Xe => f.debug_tuple("Conversion::Xe").finish(),
                    }
                }
            }
            impl Conversion {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Conversion {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Conversion::Se,
                        1 => Conversion::Te,
                        2 => Conversion::Ve,
                        3 => Conversion::Xe,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Connective {
                Je,
                Ja,
                Jo,
                Ju,
            }
            impl ::core::fmt::Debug for Connective {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Connective::Je => f.debug_tuple("Connective::Je").finish(),
                        Connective::Ja => f.debug_tuple("Connective::Ja").finish(),
                        Connective::Jo => f.debug_tuple("Connective::Jo").finish(),
                        Connective::Ju => f.debug_tuple("Connective::Ju").finish(),
                    }
                }
            }
            impl Connective {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Connective {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Connective::Je,
                        1 => Connective::Ja,
                        2 => Connective::Jo,
                        3 => Connective::Ju,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Gadri {
                Lo,
                Le,
                La,
                RoLo,
                RoLe,
            }
            impl ::core::fmt::Debug for Gadri {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Gadri::Lo => f.debug_tuple("Gadri::Lo").finish(),
                        Gadri::Le => f.debug_tuple("Gadri::Le").finish(),
                        Gadri::La => f.debug_tuple("Gadri::La").finish(),
                        Gadri::RoLo => f.debug_tuple("Gadri::RoLo").finish(),
                        Gadri::RoLe => f.debug_tuple("Gadri::RoLe").finish(),
                    }
                }
            }
            impl Gadri {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Gadri {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Gadri::Lo,
                        1 => Gadri::Le,
                        2 => Gadri::La,
                        3 => Gadri::RoLo,
                        4 => Gadri::RoLe,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum AbstractionKind {
                Nu,
                Duhu,
                Ka,
                Ni,
                Siho,
            }
            impl ::core::fmt::Debug for AbstractionKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        AbstractionKind::Nu => {
                            f.debug_tuple("AbstractionKind::Nu").finish()
                        }
                        AbstractionKind::Duhu => {
                            f.debug_tuple("AbstractionKind::Duhu").finish()
                        }
                        AbstractionKind::Ka => {
                            f.debug_tuple("AbstractionKind::Ka").finish()
                        }
                        AbstractionKind::Ni => {
                            f.debug_tuple("AbstractionKind::Ni").finish()
                        }
                        AbstractionKind::Siho => {
                            f.debug_tuple("AbstractionKind::Siho").finish()
                        }
                    }
                }
            }
            impl AbstractionKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> AbstractionKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => AbstractionKind::Nu,
                        1 => AbstractionKind::Duhu,
                        2 => AbstractionKind::Ka,
                        3 => AbstractionKind::Ni,
                        4 => AbstractionKind::Siho,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum RelClauseKind {
                Poi,
                Noi,
            }
            impl ::core::fmt::Debug for RelClauseKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        RelClauseKind::Poi => {
                            f.debug_tuple("RelClauseKind::Poi").finish()
                        }
                        RelClauseKind::Noi => {
                            f.debug_tuple("RelClauseKind::Noi").finish()
                        }
                    }
                }
            }
            impl RelClauseKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> RelClauseKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => RelClauseKind::Poi,
                        1 => RelClauseKind::Noi,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct RelClause {
                pub kind: RelClauseKind,
                pub body_sentence: u32,
            }
            impl ::core::fmt::Debug for RelClause {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RelClause")
                        .field("kind", &self.kind)
                        .field("body-sentence", &self.body_sentence)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub enum Sumti {
                ProSumti(_rt::String),
                Description((Gadri, SelbriId)),
                Name(_rt::String),
                QuotedLiteral(_rt::String),
                Unspecified,
                Tagged((PlaceTag, SumtiId)),
                ModalTagged((ModalTag, SumtiId)),
                Restricted((SumtiId, RelClause)),
                Number(f64),
                /// Sumti connective: left .e/.a/.o/.u [nai] right
                /// Fields: (left-sumti-id, connective, right-negated, right-sumti-id)
                Connected((SumtiId, Connective, bool, SumtiId)),
                /// Numeric quantifier + description: PA lo/le selbri [ku]
                /// Fields: (count, gadri, selbri-id)
                QuantifiedDescription((u32, Gadri, SelbriId)),
            }
            impl ::core::fmt::Debug for Sumti {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Sumti::ProSumti(e) => {
                            f.debug_tuple("Sumti::ProSumti").field(e).finish()
                        }
                        Sumti::Description(e) => {
                            f.debug_tuple("Sumti::Description").field(e).finish()
                        }
                        Sumti::Name(e) => f.debug_tuple("Sumti::Name").field(e).finish(),
                        Sumti::QuotedLiteral(e) => {
                            f.debug_tuple("Sumti::QuotedLiteral").field(e).finish()
                        }
                        Sumti::Unspecified => {
                            f.debug_tuple("Sumti::Unspecified").finish()
                        }
                        Sumti::Tagged(e) => {
                            f.debug_tuple("Sumti::Tagged").field(e).finish()
                        }
                        Sumti::ModalTagged(e) => {
                            f.debug_tuple("Sumti::ModalTagged").field(e).finish()
                        }
                        Sumti::Restricted(e) => {
                            f.debug_tuple("Sumti::Restricted").field(e).finish()
                        }
                        Sumti::Number(e) => {
                            f.debug_tuple("Sumti::Number").field(e).finish()
                        }
                        Sumti::Connected(e) => {
                            f.debug_tuple("Sumti::Connected").field(e).finish()
                        }
                        Sumti::QuantifiedDescription(e) => {
                            f.debug_tuple("Sumti::QuantifiedDescription")
                                .field(e)
                                .finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub enum Selbri {
                Root(_rt::String),
                Compound(_rt::Vec<_rt::String>),
                Tanru((SelbriId, SelbriId)),
                Converted((Conversion, SelbriId)),
                Negated(SelbriId),
                Grouped(SelbriId),
                WithArgs((SelbriId, _rt::Vec<SumtiId>)),
                Connected((SelbriId, Connective, SelbriId)),
                /// Abstraction: inner bridi lives in sentences[u32].
                /// Arity is 1 (x1 = reified entity: event/proposition/property/quantity/concept).
                Abstraction((AbstractionKind, u32)),
            }
            impl ::core::fmt::Debug for Selbri {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Selbri::Root(e) => {
                            f.debug_tuple("Selbri::Root").field(e).finish()
                        }
                        Selbri::Compound(e) => {
                            f.debug_tuple("Selbri::Compound").field(e).finish()
                        }
                        Selbri::Tanru(e) => {
                            f.debug_tuple("Selbri::Tanru").field(e).finish()
                        }
                        Selbri::Converted(e) => {
                            f.debug_tuple("Selbri::Converted").field(e).finish()
                        }
                        Selbri::Negated(e) => {
                            f.debug_tuple("Selbri::Negated").field(e).finish()
                        }
                        Selbri::Grouped(e) => {
                            f.debug_tuple("Selbri::Grouped").field(e).finish()
                        }
                        Selbri::WithArgs(e) => {
                            f.debug_tuple("Selbri::WithArgs").field(e).finish()
                        }
                        Selbri::Connected(e) => {
                            f.debug_tuple("Selbri::Connected").field(e).finish()
                        }
                        Selbri::Abstraction(e) => {
                            f.debug_tuple("Selbri::Abstraction").field(e).finish()
                        }
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Tense {
                Pu,
                Ca,
                Ba,
            }
            impl ::core::fmt::Debug for Tense {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Tense::Pu => f.debug_tuple("Tense::Pu").finish(),
                        Tense::Ca => f.debug_tuple("Tense::Ca").finish(),
                        Tense::Ba => f.debug_tuple("Tense::Ba").finish(),
                    }
                }
            }
            impl Tense {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Tense {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Tense::Pu,
                        1 => Tense::Ca,
                        2 => Tense::Ba,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct Bridi {
                pub relation: SelbriId,
                pub head_terms: _rt::Vec<SumtiId>,
                pub tail_terms: _rt::Vec<SumtiId>,
                pub negated: bool,
                pub tense: Option<Tense>,
            }
            impl ::core::fmt::Debug for Bridi {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Bridi")
                        .field("relation", &self.relation)
                        .field("head-terms", &self.head_terms)
                        .field("tail-terms", &self.tail_terms)
                        .field("negated", &self.negated)
                        .field("tense", &self.tense)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum SentenceConnective {
                GanaiGi,
                GeGi,
                GaGi,
            }
            impl ::core::fmt::Debug for SentenceConnective {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        SentenceConnective::GanaiGi => {
                            f.debug_tuple("SentenceConnective::GanaiGi").finish()
                        }
                        SentenceConnective::GeGi => {
                            f.debug_tuple("SentenceConnective::GeGi").finish()
                        }
                        SentenceConnective::GaGi => {
                            f.debug_tuple("SentenceConnective::GaGi").finish()
                        }
                    }
                }
            }
            impl SentenceConnective {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> SentenceConnective {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => SentenceConnective::GanaiGi,
                        1 => SentenceConnective::GeGi,
                        2 => SentenceConnective::GaGi,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub enum Sentence {
                Simple(Bridi),
                Connected((SentenceConnective, u32, u32)),
            }
            impl ::core::fmt::Debug for Sentence {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Sentence::Simple(e) => {
                            f.debug_tuple("Sentence::Simple").field(e).finish()
                        }
                        Sentence::Connected(e) => {
                            f.debug_tuple("Sentence::Connected").field(e).finish()
                        }
                    }
                }
            }
            /// Update ast-buffer to hold the new `sentence` variant:
            #[derive(Clone)]
            pub struct AstBuffer {
                pub selbris: _rt::Vec<Selbri>,
                pub sumtis: _rt::Vec<Sumti>,
                pub sentences: _rt::Vec<Sentence>,
                /// <-- CHANGED from bridi to sentence
                pub roots: _rt::Vec<u32>,
            }
            impl ::core::fmt::Debug for AstBuffer {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("AstBuffer")
                        .field("selbris", &self.selbris)
                        .field("sumtis", &self.sumtis)
                        .field("sentences", &self.sentences)
                        .field("roots", &self.roots)
                        .finish()
                }
            }
            /// --- Logic Types ---
            #[derive(Clone)]
            pub enum LogicalTerm {
                Variable(_rt::String),
                Constant(_rt::String),
                Description(_rt::String),
                Unspecified,
                Number(f64),
            }
            impl ::core::fmt::Debug for LogicalTerm {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogicalTerm::Variable(e) => {
                            f.debug_tuple("LogicalTerm::Variable").field(e).finish()
                        }
                        LogicalTerm::Constant(e) => {
                            f.debug_tuple("LogicalTerm::Constant").field(e).finish()
                        }
                        LogicalTerm::Description(e) => {
                            f.debug_tuple("LogicalTerm::Description").field(e).finish()
                        }
                        LogicalTerm::Unspecified => {
                            f.debug_tuple("LogicalTerm::Unspecified").finish()
                        }
                        LogicalTerm::Number(e) => {
                            f.debug_tuple("LogicalTerm::Number").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub enum LogicNode {
                Predicate((_rt::String, _rt::Vec<LogicalTerm>)),
                AndNode((u32, u32)),
                OrNode((u32, u32)),
                NotNode(u32),
                ExistsNode((_rt::String, u32)),
                ForAllNode((_rt::String, u32)),
                PastNode(u32),
                PresentNode(u32),
                FutureNode(u32),
                /// Exactly N entities satisfy the body: Count(variable-name, count, body-node-id)
                CountNode((_rt::String, u32, u32)),
            }
            impl ::core::fmt::Debug for LogicNode {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogicNode::Predicate(e) => {
                            f.debug_tuple("LogicNode::Predicate").field(e).finish()
                        }
                        LogicNode::AndNode(e) => {
                            f.debug_tuple("LogicNode::AndNode").field(e).finish()
                        }
                        LogicNode::OrNode(e) => {
                            f.debug_tuple("LogicNode::OrNode").field(e).finish()
                        }
                        LogicNode::NotNode(e) => {
                            f.debug_tuple("LogicNode::NotNode").field(e).finish()
                        }
                        LogicNode::ExistsNode(e) => {
                            f.debug_tuple("LogicNode::ExistsNode").field(e).finish()
                        }
                        LogicNode::ForAllNode(e) => {
                            f.debug_tuple("LogicNode::ForAllNode").field(e).finish()
                        }
                        LogicNode::PastNode(e) => {
                            f.debug_tuple("LogicNode::PastNode").field(e).finish()
                        }
                        LogicNode::PresentNode(e) => {
                            f.debug_tuple("LogicNode::PresentNode").field(e).finish()
                        }
                        LogicNode::FutureNode(e) => {
                            f.debug_tuple("LogicNode::FutureNode").field(e).finish()
                        }
                        LogicNode::CountNode(e) => {
                            f.debug_tuple("LogicNode::CountNode").field(e).finish()
                        }
                    }
                }
            }
            #[derive(Clone)]
            pub struct LogicBuffer {
                pub nodes: _rt::Vec<LogicNode>,
                pub roots: _rt::Vec<u32>,
            }
            impl ::core::fmt::Debug for LogicBuffer {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LogicBuffer")
                        .field("nodes", &self.nodes)
                        .field("roots", &self.roots)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod lojban {
        pub mod nesy {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod semantics {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type AstBuffer = super::super::super::super::lojban::nesy::ast_types::AstBuffer;
                pub type LogicBuffer = super::super::super::super::lojban::nesy::ast_types::LogicBuffer;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_compile_buffer_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: *mut u8,
                    arg7: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base26 = arg0;
                    let len26 = arg1;
                    let mut result26 = _rt::Vec::with_capacity(len26);
                    for i in 0..len26 {
                        let base = base26
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e26 = {
                            let l0 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::lojban::nesy::ast_types::Selbri as V25;
                            let v25 = match l0 {
                                0 => {
                                    let e25 = {
                                        let l1 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l2 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len3 = l2;
                                        let bytes3 = _rt::Vec::from_raw_parts(
                                            l1.cast(),
                                            len3,
                                            len3,
                                        );
                                        _rt::string_lift(bytes3)
                                    };
                                    V25::Root(e25)
                                }
                                1 => {
                                    let e25 = {
                                        let l4 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let base9 = l4;
                                        let len9 = l5;
                                        let mut result9 = _rt::Vec::with_capacity(len9);
                                        for i in 0..len9 {
                                            let base = base9
                                                .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                            let e9 = {
                                                let l6 = *base.add(0).cast::<*mut u8>();
                                                let l7 = *base
                                                    .add(::core::mem::size_of::<*const u8>())
                                                    .cast::<usize>();
                                                let len8 = l7;
                                                let bytes8 = _rt::Vec::from_raw_parts(
                                                    l6.cast(),
                                                    len8,
                                                    len8,
                                                );
                                                _rt::string_lift(bytes8)
                                            };
                                            result9.push(e9);
                                        }
                                        _rt::cabi_dealloc(
                                            base9,
                                            len9 * (2 * ::core::mem::size_of::<*const u8>()),
                                            ::core::mem::size_of::<*const u8>(),
                                        );
                                        result9
                                    };
                                    V25::Compound(e25)
                                }
                                2 => {
                                    let e25 = {
                                        let l10 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l11 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (l10 as u32, l11 as u32)
                                    };
                                    V25::Tanru(e25)
                                }
                                3 => {
                                    let e25 = {
                                        let l12 = i32::from(
                                            *base.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                        );
                                        let l13 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::Conversion::_lift(
                                                l12 as u8,
                                            ),
                                            l13 as u32,
                                        )
                                    };
                                    V25::Converted(e25)
                                }
                                4 => {
                                    let e25 = {
                                        let l14 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l14 as u32
                                    };
                                    V25::Negated(e25)
                                }
                                5 => {
                                    let e25 = {
                                        let l15 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l15 as u32
                                    };
                                    V25::Grouped(e25)
                                }
                                6 => {
                                    let e25 = {
                                        let l16 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l17 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l18 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len19 = l18;
                                        (
                                            l16 as u32,
                                            _rt::Vec::from_raw_parts(l17.cast(), len19, len19),
                                        )
                                    };
                                    V25::WithArgs(e25)
                                }
                                7 => {
                                    let e25 = {
                                        let l20 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l21 = i32::from(
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        let l22 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (
                                            l20 as u32,
                                            super::super::super::super::lojban::nesy::ast_types::Connective::_lift(
                                                l21 as u8,
                                            ),
                                            l22 as u32,
                                        )
                                    };
                                    V25::Connected(e25)
                                }
                                n => {
                                    debug_assert_eq!(n, 8, "invalid enum discriminant");
                                    let e25 = {
                                        let l23 = i32::from(
                                            *base.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                        );
                                        let l24 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::AbstractionKind::_lift(
                                                l23 as u8,
                                            ),
                                            l24 as u32,
                                        )
                                    };
                                    V25::Abstraction(e25)
                                }
                            };
                            v25
                        };
                        result26.push(e26);
                    }
                    _rt::cabi_dealloc(
                        base26,
                        len26 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let base58 = arg2;
                    let len58 = arg3;
                    let mut result58 = _rt::Vec::with_capacity(len58);
                    for i in 0..len58 {
                        let base = base58.add(i * 24);
                        let e58 = {
                            let l27 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::lojban::nesy::ast_types::Sumti as V57;
                            let v57 = match l27 {
                                0 => {
                                    let e57 = {
                                        let l28 = *base.add(8).cast::<*mut u8>();
                                        let l29 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len30 = l29;
                                        let bytes30 = _rt::Vec::from_raw_parts(
                                            l28.cast(),
                                            len30,
                                            len30,
                                        );
                                        _rt::string_lift(bytes30)
                                    };
                                    V57::ProSumti(e57)
                                }
                                1 => {
                                    let e57 = {
                                        let l31 = i32::from(*base.add(8).cast::<u8>());
                                        let l32 = *base.add(12).cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::Gadri::_lift(
                                                l31 as u8,
                                            ),
                                            l32 as u32,
                                        )
                                    };
                                    V57::Description(e57)
                                }
                                2 => {
                                    let e57 = {
                                        let l33 = *base.add(8).cast::<*mut u8>();
                                        let l34 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len35 = l34;
                                        let bytes35 = _rt::Vec::from_raw_parts(
                                            l33.cast(),
                                            len35,
                                            len35,
                                        );
                                        _rt::string_lift(bytes35)
                                    };
                                    V57::Name(e57)
                                }
                                3 => {
                                    let e57 = {
                                        let l36 = *base.add(8).cast::<*mut u8>();
                                        let l37 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len38 = l37;
                                        let bytes38 = _rt::Vec::from_raw_parts(
                                            l36.cast(),
                                            len38,
                                            len38,
                                        );
                                        _rt::string_lift(bytes38)
                                    };
                                    V57::QuotedLiteral(e57)
                                }
                                4 => V57::Unspecified,
                                5 => {
                                    let e57 = {
                                        let l39 = i32::from(*base.add(8).cast::<u8>());
                                        let l40 = *base.add(12).cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::PlaceTag::_lift(
                                                l39 as u8,
                                            ),
                                            l40 as u32,
                                        )
                                    };
                                    V57::Tagged(e57)
                                }
                                6 => {
                                    let e57 = {
                                        let l41 = i32::from(*base.add(8).cast::<u8>());
                                        use super::super::super::super::lojban::nesy::ast_types::ModalTag as V44;
                                        let v44 = match l41 {
                                            0 => {
                                                let e44 = {
                                                    let l42 = i32::from(*base.add(12).cast::<u8>());
                                                    super::super::super::super::lojban::nesy::ast_types::BaiTag::_lift(
                                                        l42 as u8,
                                                    )
                                                };
                                                V44::Fixed(e44)
                                            }
                                            n => {
                                                debug_assert_eq!(n, 1, "invalid enum discriminant");
                                                let e44 = {
                                                    let l43 = *base.add(12).cast::<i32>();
                                                    l43 as u32
                                                };
                                                V44::Fio(e44)
                                            }
                                        };
                                        let l45 = *base.add(16).cast::<i32>();
                                        (v44, l45 as u32)
                                    };
                                    V57::ModalTagged(e57)
                                }
                                7 => {
                                    let e57 = {
                                        let l46 = *base.add(8).cast::<i32>();
                                        let l47 = i32::from(*base.add(12).cast::<u8>());
                                        let l48 = *base.add(16).cast::<i32>();
                                        (
                                            l46 as u32,
                                            super::super::super::super::lojban::nesy::ast_types::RelClause {
                                                kind: super::super::super::super::lojban::nesy::ast_types::RelClauseKind::_lift(
                                                    l47 as u8,
                                                ),
                                                body_sentence: l48 as u32,
                                            },
                                        )
                                    };
                                    V57::Restricted(e57)
                                }
                                8 => {
                                    let e57 = {
                                        let l49 = *base.add(8).cast::<f64>();
                                        l49
                                    };
                                    V57::Number(e57)
                                }
                                9 => {
                                    let e57 = {
                                        let l50 = *base.add(8).cast::<i32>();
                                        let l51 = i32::from(*base.add(12).cast::<u8>());
                                        let l52 = i32::from(*base.add(13).cast::<u8>());
                                        let l53 = *base.add(16).cast::<i32>();
                                        (
                                            l50 as u32,
                                            super::super::super::super::lojban::nesy::ast_types::Connective::_lift(
                                                l51 as u8,
                                            ),
                                            _rt::bool_lift(l52 as u8),
                                            l53 as u32,
                                        )
                                    };
                                    V57::Connected(e57)
                                }
                                n => {
                                    debug_assert_eq!(n, 10, "invalid enum discriminant");
                                    let e57 = {
                                        let l54 = *base.add(8).cast::<i32>();
                                        let l55 = i32::from(*base.add(12).cast::<u8>());
                                        let l56 = *base.add(16).cast::<i32>();
                                        (
                                            l54 as u32,
                                            super::super::super::super::lojban::nesy::ast_types::Gadri::_lift(
                                                l55 as u8,
                                            ),
                                            l56 as u32,
                                        )
                                    };
                                    V57::QuantifiedDescription(e57)
                                }
                            };
                            v57
                        };
                        result58.push(e58);
                    }
                    _rt::cabi_dealloc(base58, len58 * 24, 8);
                    let base74 = arg4;
                    let len74 = arg5;
                    let mut result74 = _rt::Vec::with_capacity(len74);
                    for i in 0..len74 {
                        let base = base74
                            .add(i * (7 * ::core::mem::size_of::<*const u8>()));
                        let e74 = {
                            let l59 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::lojban::nesy::ast_types::Sentence as V73;
                            let v73 = match l59 {
                                0 => {
                                    let e73 = {
                                        let l60 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l61 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l62 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len63 = l62;
                                        let l64 = *base
                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l65 = *base
                                            .add(5 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len66 = l65;
                                        let l67 = i32::from(
                                            *base
                                                .add(6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        let l68 = i32::from(
                                            *base
                                                .add(1 + 6 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        super::super::super::super::lojban::nesy::ast_types::Bridi {
                                            relation: l60 as u32,
                                            head_terms: _rt::Vec::from_raw_parts(
                                                l61.cast(),
                                                len63,
                                                len63,
                                            ),
                                            tail_terms: _rt::Vec::from_raw_parts(
                                                l64.cast(),
                                                len66,
                                                len66,
                                            ),
                                            negated: _rt::bool_lift(l67 as u8),
                                            tense: match l68 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l69 = i32::from(
                                                            *base
                                                                .add(2 + 6 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<u8>(),
                                                        );
                                                        super::super::super::super::lojban::nesy::ast_types::Tense::_lift(
                                                            l69 as u8,
                                                        )
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                        }
                                    };
                                    V73::Simple(e73)
                                }
                                n => {
                                    debug_assert_eq!(n, 1, "invalid enum discriminant");
                                    let e73 = {
                                        let l70 = i32::from(
                                            *base.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                        );
                                        let l71 = *base
                                            .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        let l72 = *base
                                            .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        (
                                            super::super::super::super::lojban::nesy::ast_types::SentenceConnective::_lift(
                                                l70 as u8,
                                            ),
                                            l71 as u32,
                                            l72 as u32,
                                        )
                                    };
                                    V73::Connected(e73)
                                }
                            };
                            v73
                        };
                        result74.push(e74);
                    }
                    _rt::cabi_dealloc(
                        base74,
                        len74 * (7 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let len75 = arg7;
                    let result76 = T::compile_buffer(super::super::super::super::lojban::nesy::ast_types::AstBuffer {
                        selbris: result26,
                        sumtis: result58,
                        sentences: result74,
                        roots: _rt::Vec::from_raw_parts(arg6.cast(), len75, len75),
                    });
                    let ptr77 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result76 {
                        Ok(e) => {
                            *ptr77.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::lojban::nesy::ast_types::LogicBuffer {
                                nodes: nodes78,
                                roots: roots78,
                            } = e;
                            let vec95 = nodes78;
                            let len95 = vec95.len();
                            let layout95 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec95.len() * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result95 = if layout95.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout95).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout95);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec95.into_iter().enumerate() {
                                let base = result95
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    use super::super::super::super::lojban::nesy::ast_types::LogicNode as V94;
                                    match e {
                                        V94::Predicate(e) => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                            let (t79_0, t79_1) = e;
                                            let vec80 = (t79_0.into_bytes()).into_boxed_slice();
                                            let ptr80 = vec80.as_ptr().cast::<u8>();
                                            let len80 = vec80.len();
                                            ::core::mem::forget(vec80);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len80;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr80.cast_mut();
                                            let vec85 = t79_1;
                                            let len85 = vec85.len();
                                            let layout85 = _rt::alloc::Layout::from_size_align_unchecked(
                                                vec85.len() * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                                8,
                                            );
                                            let result85 = if layout85.size() != 0 {
                                                let ptr = _rt::alloc::alloc(layout85).cast::<u8>();
                                                if ptr.is_null() {
                                                    _rt::alloc::handle_alloc_error(layout85);
                                                }
                                                ptr
                                            } else {
                                                ::core::ptr::null_mut()
                                            };
                                            for (i, e) in vec85.into_iter().enumerate() {
                                                let base = result85
                                                    .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    use super::super::super::super::lojban::nesy::ast_types::LogicalTerm as V84;
                                                    match e {
                                                        V84::Variable(e) => {
                                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                                            let vec81 = (e.into_bytes()).into_boxed_slice();
                                                            let ptr81 = vec81.as_ptr().cast::<u8>();
                                                            let len81 = vec81.len();
                                                            ::core::mem::forget(vec81);
                                                            *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>() = len81;
                                                            *base.add(8).cast::<*mut u8>() = ptr81.cast_mut();
                                                        }
                                                        V84::Constant(e) => {
                                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                                            let vec82 = (e.into_bytes()).into_boxed_slice();
                                                            let ptr82 = vec82.as_ptr().cast::<u8>();
                                                            let len82 = vec82.len();
                                                            ::core::mem::forget(vec82);
                                                            *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>() = len82;
                                                            *base.add(8).cast::<*mut u8>() = ptr82.cast_mut();
                                                        }
                                                        V84::Description(e) => {
                                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                                            let vec83 = (e.into_bytes()).into_boxed_slice();
                                                            let ptr83 = vec83.as_ptr().cast::<u8>();
                                                            let len83 = vec83.len();
                                                            ::core::mem::forget(vec83);
                                                            *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>() = len83;
                                                            *base.add(8).cast::<*mut u8>() = ptr83.cast_mut();
                                                        }
                                                        V84::Unspecified => {
                                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                                        }
                                                        V84::Number(e) => {
                                                            *base.add(0).cast::<u8>() = (4i32) as u8;
                                                            *base.add(8).cast::<f64>() = _rt::as_f64(e);
                                                        }
                                                    }
                                                }
                                            }
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len85;
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = result85;
                                        }
                                        V94::AndNode(e) => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                            let (t86_0, t86_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t86_0);
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t86_1);
                                        }
                                        V94::OrNode(e) => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                            let (t87_0, t87_1) = e;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t87_0);
                                            *base
                                                .add(4 + 1 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t87_1);
                                        }
                                        V94::NotNode(e) => {
                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V94::ExistsNode(e) => {
                                            *base.add(0).cast::<u8>() = (4i32) as u8;
                                            let (t88_0, t88_1) = e;
                                            let vec89 = (t88_0.into_bytes()).into_boxed_slice();
                                            let ptr89 = vec89.as_ptr().cast::<u8>();
                                            let len89 = vec89.len();
                                            ::core::mem::forget(vec89);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len89;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr89.cast_mut();
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t88_1);
                                        }
                                        V94::ForAllNode(e) => {
                                            *base.add(0).cast::<u8>() = (5i32) as u8;
                                            let (t90_0, t90_1) = e;
                                            let vec91 = (t90_0.into_bytes()).into_boxed_slice();
                                            let ptr91 = vec91.as_ptr().cast::<u8>();
                                            let len91 = vec91.len();
                                            ::core::mem::forget(vec91);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len91;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr91.cast_mut();
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t90_1);
                                        }
                                        V94::PastNode(e) => {
                                            *base.add(0).cast::<u8>() = (6i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V94::PresentNode(e) => {
                                            *base.add(0).cast::<u8>() = (7i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V94::FutureNode(e) => {
                                            *base.add(0).cast::<u8>() = (8i32) as u8;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(e);
                                        }
                                        V94::CountNode(e) => {
                                            *base.add(0).cast::<u8>() = (9i32) as u8;
                                            let (t92_0, t92_1, t92_2) = e;
                                            let vec93 = (t92_0.into_bytes()).into_boxed_slice();
                                            let ptr93 = vec93.as_ptr().cast::<u8>();
                                            let len93 = vec93.len();
                                            ::core::mem::forget(vec93);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len93;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr93.cast_mut();
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t92_1);
                                            *base
                                                .add(4 + 3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<i32>() = _rt::as_i32(t92_2);
                                        }
                                    }
                                }
                            }
                            *ptr77
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len95;
                            *ptr77
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result95;
                            let vec96 = (roots78).into_boxed_slice();
                            let ptr96 = vec96.as_ptr().cast::<u8>();
                            let len96 = vec96.len();
                            ::core::mem::forget(vec96);
                            *ptr77
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len96;
                            *ptr77
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr96.cast_mut();
                        }
                        Err(e) => {
                            *ptr77.add(0).cast::<u8>() = (1i32) as u8;
                            let vec97 = (e.into_bytes()).into_boxed_slice();
                            let ptr97 = vec97.as_ptr().cast::<u8>();
                            let len97 = vec97.len();
                            ::core::mem::forget(vec97);
                            *ptr77
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len97;
                            *ptr77
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr97.cast_mut();
                        }
                    };
                    ptr77
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_compile_buffer<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base22 = l1;
                            let len22 = l2;
                            for i in 0..len22 {
                                let base = base22
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = i32::from(*base.add(0).cast::<u8>());
                                    match l3 {
                                        0 => {
                                            let l4 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l5 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l4, l5, 1);
                                            let l6 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l7 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let base15 = l6;
                                            let len15 = l7;
                                            for i in 0..len15 {
                                                let base = base15
                                                    .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let l8 = i32::from(*base.add(0).cast::<u8>());
                                                    match l8 {
                                                        0 => {
                                                            let l9 = *base.add(8).cast::<*mut u8>();
                                                            let l10 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            _rt::cabi_dealloc(l9, l10, 1);
                                                        }
                                                        1 => {
                                                            let l11 = *base.add(8).cast::<*mut u8>();
                                                            let l12 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            _rt::cabi_dealloc(l11, l12, 1);
                                                        }
                                                        2 => {
                                                            let l13 = *base.add(8).cast::<*mut u8>();
                                                            let l14 = *base
                                                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                                                .cast::<usize>();
                                                            _rt::cabi_dealloc(l13, l14, 1);
                                                        }
                                                        3 => {}
                                                        _ => {}
                                                    }
                                                }
                                            }
                                            _rt::cabi_dealloc(
                                                base15,
                                                len15 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                                                8,
                                            );
                                        }
                                        1 => {}
                                        2 => {}
                                        3 => {}
                                        4 => {
                                            let l16 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l17 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l16, l17, 1);
                                        }
                                        5 => {
                                            let l18 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l19 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l18, l19, 1);
                                        }
                                        6 => {}
                                        7 => {}
                                        8 => {}
                                        _ => {
                                            let l20 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l21 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l20, l21, 1);
                                        }
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base22,
                                len22 * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l23 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l24 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base25 = l23;
                            let len25 = l24;
                            _rt::cabi_dealloc(base25, len25 * 4, 4);
                        }
                        _ => {
                            let l26 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l27 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l26, l27, 1);
                        }
                    }
                }
                pub trait Guest {
                    fn compile_buffer(
                        ast: AstBuffer,
                    ) -> Result<LogicBuffer, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_lojban_nesy_semantics_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "lojban:nesy/semantics@0.1.0#compile-buffer")] unsafe extern "C"
                        fn export_compile_buffer(arg0 : * mut u8, arg1 : usize, arg2 : *
                        mut u8, arg3 : usize, arg4 : * mut u8, arg5 : usize, arg6 : * mut
                        u8, arg7 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_compile_buffer_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7) } } #[unsafe (export_name =
                        "cabi_post_lojban:nesy/semantics@0.1.0#compile-buffer")] unsafe
                        extern "C" fn _post_return_compile_buffer(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_compile_buffer::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_lojban_nesy_semantics_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::alloc;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_semantics_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::lojban::nesy::semantics::__export_lojban_nesy_semantics_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::lojban::nesy::semantics);
    };
}
#[doc(inline)]
pub(crate) use __export_semantics_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:lojban:nesy@0.1.0:semantics-component:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1630] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd4\x0b\x01A\x02\x01\
A\x06\x01BC\x01y\x04\0\x09selbri-id\x03\0\0\x01y\x04\0\x08sumti-id\x03\0\x02\x01\
m\x05\x02fa\x02fe\x02fi\x02fo\x02fu\x04\0\x09place-tag\x03\0\x04\x01m\x06\x03ria\
\x03nii\x03mui\x03kiu\x03pio\x03bai\x04\0\x07bai-tag\x03\0\x06\x01q\x02\x05fixed\
\x01\x07\0\x03fio\x01\x01\0\x04\0\x09modal-tag\x03\0\x08\x01m\x04\x02se\x02te\x02\
ve\x02xe\x04\0\x0aconversion\x03\0\x0a\x01m\x04\x02je\x02ja\x02jo\x02ju\x04\0\x0a\
connective\x03\0\x0c\x01m\x05\x02lo\x02le\x02la\x05ro-lo\x05ro-le\x04\0\x05gadri\
\x03\0\x0e\x01m\x05\x02nu\x04duhu\x02ka\x02ni\x04siho\x04\0\x10abstraction-kind\x03\
\0\x10\x01m\x02\x03poi\x03noi\x04\0\x0frel-clause-kind\x03\0\x12\x01r\x02\x04kin\
d\x13\x0dbody-sentencey\x04\0\x0arel-clause\x03\0\x14\x01o\x02\x0f\x01\x01o\x02\x05\
\x03\x01o\x02\x09\x03\x01o\x02\x03\x15\x01o\x04\x03\x0d\x7f\x03\x01o\x03y\x0f\x01\
\x01q\x0b\x09pro-sumti\x01s\0\x0bdescription\x01\x16\0\x04name\x01s\0\x0equoted-\
literal\x01s\0\x0bunspecified\0\0\x06tagged\x01\x17\0\x0cmodal-tagged\x01\x18\0\x0a\
restricted\x01\x19\0\x06number\x01u\0\x09connected\x01\x1a\0\x16quantified-descr\
iption\x01\x1b\0\x04\0\x05sumti\x03\0\x1c\x01ps\x01o\x02\x01\x01\x01o\x02\x0b\x01\
\x01p\x03\x01o\x02\x01!\x01o\x03\x01\x0d\x01\x01o\x02\x11y\x01q\x09\x04root\x01s\
\0\x08compound\x01\x1e\0\x05tanru\x01\x1f\0\x09converted\x01\x20\0\x07negated\x01\
\x01\0\x07grouped\x01\x01\0\x09with-args\x01\"\0\x09connected\x01#\0\x0babstract\
ion\x01$\0\x04\0\x06selbri\x03\0%\x01m\x03\x02pu\x02ca\x02ba\x04\0\x05tense\x03\0\
'\x01k(\x01r\x05\x08relation\x01\x0ahead-terms!\x0atail-terms!\x07negated\x7f\x05\
tense)\x04\0\x05bridi\x03\0*\x01m\x03\x08ganai-gi\x05ge-gi\x05ga-gi\x04\0\x13sen\
tence-connective\x03\0,\x01o\x03-yy\x01q\x02\x06simple\x01+\0\x09connected\x01.\0\
\x04\0\x08sentence\x03\0/\x01p&\x01p\x1d\x01p0\x01py\x01r\x04\x07selbris1\x06sum\
tis2\x09sentences3\x05roots4\x04\0\x0aast-buffer\x03\05\x01q\x05\x08variable\x01\
s\0\x08constant\x01s\0\x0bdescription\x01s\0\x0bunspecified\0\0\x06number\x01u\0\
\x04\0\x0clogical-term\x03\07\x01p8\x01o\x02s9\x01o\x02yy\x01o\x02sy\x01o\x03syy\
\x01q\x0a\x09predicate\x01:\0\x08and-node\x01;\0\x07or-node\x01;\0\x08not-node\x01\
y\0\x0bexists-node\x01<\0\x0cfor-all-node\x01<\0\x09past-node\x01y\0\x0cpresent-\
node\x01y\0\x0bfuture-node\x01y\0\x0acount-node\x01=\0\x04\0\x0alogic-node\x03\0\
>\x01p?\x01r\x02\x05nodes\xc0\0\x05roots4\x04\0\x0clogic-buffer\x03\0A\x03\0\x1b\
lojban:nesy/ast-types@0.1.0\x05\0\x02\x03\0\0\x0aast-buffer\x02\x03\0\0\x0clogic\
-buffer\x01B\x07\x02\x03\x02\x01\x01\x04\0\x0aast-buffer\x03\0\0\x02\x03\x02\x01\
\x02\x04\0\x0clogic-buffer\x03\0\x02\x01j\x01\x03\x01s\x01@\x01\x03ast\x01\0\x04\
\x04\0\x0ecompile-buffer\x01\x05\x04\0\x1blojban:nesy/semantics@0.1.0\x05\x03\x04\
\0%lojban:nesy/semantics-component@0.1.0\x04\0\x0b\x19\x01\0\x13semantics-compon\
ent\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10\
wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
